In [1]:
%load_ext autoreload
%autoreload 2

# import libraries
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
import pybedtools # if on M1 chip mac while installing bedtools make sure conda config --env --set subdir osx-64 (i was on arm-64 and it could not find bedtools!!!) also install rosetta2 /usr/sbin/softwareupdate --install-rosetta --agree-to-license
from pybedtools import BedTool
import numpy as np
import gzip

# change parent directory to use tools

from pathlib import Path
os.chdir(Path.cwd().parent)
from introgression_tools import tools

!HOMEDIR='/wynton/home/capra/ychen39/'
HOMEDIR='/wynton/home/capra/ychen39/'
BEDTOOLSDIR = '/wynton/home/cbi/shared/software/CBI/bedtools2-2.31.1/bin'
# set bedtools path
pybedtools.helpers.set_bedtools_path(path=f'{BEDTOOLSDIR}')

# directories for each method's data
methods_dirs = ['yuan_2021', 'durvasula_2019', 'steinruecken_2018', 'skov_2020', 'schaefer_2021', 'hubisz_2020', 'browning_2018_updated_filtering', 
                'vernot_2016', 'sankararaman_2014', 'sankararaman_2016_1', 'sankararaman_2016_2', 'li_2024', 'skov_2018', 'iasi_2024']

In [ ]:
conda list --export | awk -F= '{print $1"=="$2}' > $HOMEDIR/introgression_methods/introgression_tools/requirements.txt

/bin/bash: conda: command not found

## Generating standardized variant-level files across introgression methods
SNPs are only available for Sankararaman14, Sankararaman16 (1 and 2), S*, Sprime, Skov20, and Skov18.

We will also make .bed files for each ancestral group.

Here, we use the introgression_tools package to generate standardized variant-level data. Vernot and CRF variant-level introgression files were generated from Bash scripts.

#### Sankararaman 2014

In [ ]:
%%bash

# set up directories
INPUTDIR="/wynton/home/capra/ychen39/introgression_methods/data/sankararaman_2014_copy/sankararaman_2014"
OUTPUTDIR="/wynton/home/capra/ychen39/introgression_methods/cleaned/introgression_tools/sankararaman_2014/"

mkdir $OUTPUTDIR

# for each population file
# add column names
echo -e "Chromosome\tEnd\tAlleleScore\tHaplotypeScore\tPopulation" > $OUTPUTDIR/neanderthal_introgressed_variants_pops.bed
# add data from each population file
for pop in $(cat $INPUTDIR/pops.EUR-ASN); do
    echo $pop
    cd $INPUTDIR/"$pop".hapmap/summaries/
    FILES=`ls --color=never *.gz`
    for file in $FILES; do
        echo $file
        # keep entries if their nean probabilities (column 11) are greater than 0.9
        gunzip -c $file | awk -v pop="$pop" '{ if ($10+0 > 0.9) print $2 "\t" $4 "\t" $10 "\t" $11 "\t" pop}' >> $OUTPUTDIR/pops.bed
    done
done
# remove extra file lines except ones starting with numbers (chromosomes), X (for chromosome X), and C (header line)
grep '^[0-9 | X | C]' $OUTPUTDIR/pops.bed > $OUTPUTDIR/neanderthal_introgressed_variants_pops.bed

mkdir: cannot create directory ‘/wynton/home/capra/ychen39/introgression_methods/cleaned/introgression_tools/sankararaman_2014/’: File exists

CEU
chr-10.thresh-90.length-0.00.gz
chr-11.thresh-90.length-0.00.gz
chr-12.thresh-90.length-0.00.gz
chr-13.thresh-90.length-0.00.gz
chr-14.thresh-90.length-0.00.gz
chr-15.thresh-90.length-0.00.gz
chr-16.thresh-90.length-0.00.gz
chr-17.thresh-90.length-0.00.gz
chr-18.thresh-90.length-0.00.gz
chr-19.thresh-90.length-0.00.gz
chr-1.thresh-90.length-0.00.gz
chr-20.thresh-90.length-0.00.gz
chr-21.thresh-90.length-0.00.gz
chr-22.thresh-90.length-0.00.gz
chr-2.thresh-90.length-0.00.gz
chr-3.thresh-90.length-0.00.gz
chr-4.thresh-90.length-0.00.gz
chr-5.thresh-90.length-0.00.gz
chr-6.thresh-90.length-0.00.gz
chr-7.thresh-90.length-0.00.gz
chr-8.thresh-90.length-0.00.gz
chr-9.thresh-90.length-0.00.gz
chr-X.thresh-90.length-0.00.gz
FIN
chr-10.thresh-90.length-0.00.gz
chr-11.thresh-90.length-0.00.gz
chr-12.thresh-90.length-0.00.gz
chr-13.thresh-90.length-0.00.gz
chr-14.thresh-90.length-0.00.gz
chr-15.thresh-90.length-0.00.gz
chr-16.thresh-90.length-0.00.gz
chr-17.thresh-90.length-0.00.gz
chr-18.thresh-90.length-0.00.gz
chr-19.thresh-90.length-0.00.gz
chr-1.thresh-90.length-0.00.gz
chr-20.thresh-90.length-0.00.gz
chr-21.thresh-90.length-0.00.gz
chr-22.thresh-90.length-0.00.gz
chr-2.thresh-90.length-0.00.gz
chr-3.thresh-90.length-0.00.gz
chr-4.thresh-90.length-0.00.gz
chr-5.thresh-90.length-0.00.gz
chr-6.thresh-90.length-0.00.gz
chr-7.thresh-90.length-0.00.gz
chr-8.thresh-90.length-0.00.gz
chr-9.thresh-90.length-0.00.gz
chr-X.thresh-90.length-0.00.gz
GBR
chr-10.thresh-90.length-0.00.gz
chr-11.thresh-90.length-0.00.gz
chr-12.thresh-90.length-0.00.gz
chr-13.thresh-90.length-0.00.gz
chr-14.thresh-90.length-0.00.gz
chr-15.thresh-90.length-0.00.gz
chr-16.thresh-90.length-0.00.gz
chr-17.thresh-90.length-0.00.gz
chr-18.thresh-90.length-0.00.gz
chr-19.thresh-90.length-0.00.gz
chr-1.thresh-90.length-0.00.gz
chr-20.thresh-90.length-0.00.gz
chr-21.thresh-90.length-0.00.gz
chr-22.thresh-90.length-0.00.gz
chr-2.thresh-90.length-0.00.gz
chr-3.thresh-90.length-0.00.gz
chr-4.thresh-90.length-0.00.gz
chr-5.thresh-90.length-0.00.gz
chr-6.thresh-90.length-0.00.gz
chr-7.thresh-90.length-0.00.gz
chr-8.thresh-90.length-0.00.gz
chr-9.thresh-90.length-0.00.gz
chr-X.thresh-90.length-0.00.gz
IBS
chr-10.thresh-90.length-0.00.gz
chr-11.thresh-90.length-0.00.gz
chr-12.thresh-90.length-0.00.gz
chr-13.thresh-90.length-0.00.gz
chr-14.thresh-90.length-0.00.gz
chr-15.thresh-90.length-0.00.gz
chr-16.thresh-90.length-0.00.gz
chr-17.thresh-90.length-0.00.gz
chr-18.thresh-90.length-0.00.gz
chr-19.thresh-90.length-0.00.gz
chr-1.thresh-90.length-0.00.gz
chr-20.thresh-90.length-0.00.gz
chr-21.thresh-90.length-0.00.gz
chr-22.thresh-90.length-0.00.gz
chr-2.thresh-90.length-0.00.gz
chr-3.thresh-90.length-0.00.gz
chr-4.thresh-90.length-0.00.gz
chr-5.thresh-90.length-0.00.gz
chr-6.thresh-90.length-0.00.gz
chr-7.thresh-90.length-0.00.gz
chr-8.thresh-90.length-0.00.gz
chr-9.thresh-90.length-0.00.gz
chr-X.thresh-90.length-0.00.gz
TSI
chr-10.thresh-90.length-0.00.gz
chr-11.thresh-90.length-0.00.gz
chr-12.thresh-90.length-0.00.gz
chr-13.thresh-90.length-0.00.gz
chr-14.thresh-90.length-0.00.gz
chr-15.thresh-90.length-0.00.gz
chr-16.thresh-90.length-0.00.gz
chr-17.thresh-90.length-0.00.gz
chr-18.thresh-90.length-0.00.gz
chr-19.thresh-90.length-0.00.gz
chr-1.thresh-90.length-0.00.gz
chr-20.thresh-90.length-0.00.gz
chr-21.thresh-90.length-0.00.gz
chr-22.thresh-90.length-0.00.gz
chr-2.thresh-90.length-0.00.gz
chr-3.thresh-90.length-0.00.gz
chr-4.thresh-90.length-0.00.gz
chr-5.thresh-90.length-0.00.gz
chr-6.thresh-90.length-0.00.gz
chr-7.thresh-90.length-0.00.gz
chr-8.thresh-90.length-0.00.gz
chr-9.thresh-90.length-0.00.gz
chr-X.thresh-90.length-0.00.gz
CHB
chr-10.thresh-90.length-0.00.gz
chr-11.thresh-90.length-0.00.gz
chr-12.thresh-90.length-0.00.gz
chr-13.thresh-90.length-0.00.gz
chr-14.thresh-90.length-0.00.gz
chr-15.thresh-90.length-0.00.gz
chr-16.thresh-90.length-0.00.gz
chr-17.thresh-90.length-0.00.gz
chr-18.thresh-90.length-0.00.gz
chr-19.thresh-90.length-0.00.gz
chr-1.thresh-90.length-0.00.gz
chr-20.thresh-90.length-0.00.gz
chr-21.thresh-90.length-0.00.gz
chr-22.thresh-90.length-0.00.gz
chr-2.thresh-90.length-0.00.gz
chr-3.thresh-90.length-0.00.gz
chr-4.thresh-90.length-0.00.gz
chr-5.thresh-90.length-0.00.gz
chr-6.thresh-90.length-0.00.gz
chr-7.thresh-90.length-0.00.gz
chr-8.thresh-90.length-0.00.gz
chr-9.thresh-90.length-0.00.gz
chr-X.thresh-90.length-0.00.gz
CHS
chr-10.thresh-90.length-0.00.gz
chr-11.thresh-90.length-0.00.gz
chr-12.thresh-90.length-0.00.gz
chr-13.thresh-90.length-0.00.gz
chr-14.thresh-90.length-0.00.gz
chr-15.thresh-90.length-0.00.gz
chr-16.thresh-90.length-0.00.gz
chr-17.thresh-90.length-0.00.gz
chr-18.thresh-90.length-0.00.gz
chr-19.thresh-90.length-0.00.gz
chr-1.thresh-90.length-0.00.gz
chr-20.thresh-90.length-0.00.gz
chr-21.thresh-90.length-0.00.gz
chr-22.thresh-90.length-0.00.gz
chr-2.thresh-90.length-0.00.gz
chr-3.thresh-90.length-0.00.gz
chr-4.thresh-90.length-0.00.gz
chr-5.thresh-90.length-0.00.gz
chr-6.thresh-90.length-0.00.gz
chr-7.thresh-90.length-0.00.gz
chr-8.thresh-90.length-0.00.gz
chr-9.thresh-90.length-0.00.gz
chr-X.thresh-90.length-0.00.gz
JPT
chr-10.thresh-90.length-0.00.gz
chr-11.thresh-90.length-0.00.gz
chr-12.thresh-90.length-0.00.gz
chr-13.thresh-90.length-0.00.gz
chr-14.thresh-90.length-0.00.gz
chr-15.thresh-90.length-0.00.gz
chr-16.thresh-90.length-0.00.gz
chr-17.thresh-90.length-0.00.gz
chr-18.thresh-90.length-0.00.gz
chr-19.thresh-90.length-0.00.gz
chr-1.thresh-90.length-0.00.gz
chr-20.thresh-90.length-0.00.gz
chr-21.thresh-90.length-0.00.gz
chr-22.thresh-90.length-0.00.gz
chr-2.thresh-90.length-0.00.gz
chr-3.thresh-90.length-0.00.gz
chr-4.thresh-90.length-0.00.gz
chr-5.thresh-90.length-0.00.gz
chr-6.thresh-90.length-0.00.gz
chr-7.thresh-90.length-0.00.gz
chr-8.thresh-90.length-0.00.gz
chr-9.thresh-90.length-0.00.gz
chr-X.thresh-90.length-0.00.gz

In [ ]:
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/neanderthal_introgressed_variants_pops.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/neanderthal_introgressed_variants.bg', 
              prefix=False, 
              save_with_header=False,
              colnames=['Chromosome', 'End', 'AlleleScore', 'HaplotypeScore', 'Ancestry'])

In [ ]:
# with chr prefix
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/sankararaman_2014_copy/neanderthal_introgressed_variants_pops.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/neanderthal_introgressed_variants_chr_prefix.bg', 
              prefix=True, 
              save_with_header=False,
              colnames=['Chromosome', 'End', 'AlleleScore', 'HaplotypeScore', 'Ancestry'])

In [ ]:
# Make EUR-specific variant files
sankararaman_2014 = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/neanderthal_introgressed_variants_pops.bed', 
                            sep='\t', low_memory=False)

sankararaman_2014['Ancestry'] = sankararaman_2014['Population'].apply(tools.map_status)

sankararaman_2014_EUR=sankararaman_2014[sankararaman_2014['Ancestry']=='EUR']

tools.save_bed_only(df=sankararaman_2014_EUR, 
         output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/neanderthal_introgressed_variants_EUR_chr_prefix.bed', prefix=True)

#### Sankararaman 2016

In [ ]:
# sankararaman 2016 - 1
# Repeat for first directory

# set up directories
INPUTDIR="/wynton/home/capra/ychen39/introgression_methods/data/sankararaman_2016/summaries/1/neandertal"
OUTPUTDIR="/wynton/home/capra/ychen39/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1"

mkdir $OUTPUTDIR

# add column names
echo -e "Chromosome\tEnd\tAlleleScore\tHaplotypeScore\tPopulation" > $OUTPUTDIR/pops.bed
# add data from each population file
for pop in $(cat $INPUTDIR/../../pops); do
    cd $INPUTDIR/"$pop"/summaries/
    FILES=`ls --color=never pred*`
    for file in $FILES; do
        echo $file
        # keep entries if their nean probabilities (column 10) are greater than 0.5
        awk -v pop="$pop" '{ if ($10+0 > 0.5) print $2 "\t" $4 "\t" $10 "\t" $11 "\t" pop}' $file >> $OUTPUTDIR/pops.bed
    done
done

# remove extra file lines except ones starting with numbers (chromosomes), X (for chromosome X), and C (header line)
grep '^[0-9 | X | C]' $OUTPUTDIR/pops.bed > $OUTPUTDIR/neanderthal_introgressed_variants_pops.bed

In [ ]:
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/neanderthal_introgressed_variants_pops.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/neanderthal_introgressed_variants.bg', 
              prefix=False, 
              save_with_header=False)

In [ ]:
# with chr prefix
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/neanderthal_introgressed_variants_pops.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/neanderthal_introgressed_variants_chr_prefix.bg', 
              prefix=True,
              save_with_header=False)

In [ ]:
# Make EUR variant files
sankararaman_2016_1 = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/neanderthal_introgressed_variants_pops.bed', 
                            sep='\t', low_memory=False)

sankararaman_2016_1['Ancestry'] = sankararaman_2016_1['Population'].apply(tools.map_status)
sankararaman_2016_1_EUR=sankararaman_2016_1[sankararaman_2016_1['Ancestry']=='EUR']

tools.save_bed_only(df=sankararaman_2016_1_EUR, 
         output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/neanderthal_introgressed_variants_EUR_chr_prefix.bed', 
         prefix=True)

In [ ]:
# sankararaman 2016 - 2
%%bash

# set up directories
INPUTDIR="/wynton/home/capra/ychen39/introgression_methods/data/sankararaman_2016/summaries/2/neandertal"
OUTPUTDIR="/wynton/home/capra/ychen39/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2"

# add column names
echo -e "Chromosome\tEnd\tAlleleScore\tHaplotypeScore\tPopulation" > $OUTPUTDIR/pops.bed
# add data from each population file
for pop in $(cat $INPUTDIR/../../pops); do
    cd $INPUTDIR/"$pop"/summaries/
    FILES=`ls --color=never pred*`
    for file in $FILES; do
        echo $file
        # keep entries if their nean probabilities from derived alleles (column 10) are greater than 0.5
        awk -v pop="$pop" '{print $1 print $2 "\t" $4 "\t" $10 "\t" $11 "\t" pop}' $file >> $OUTPUTDIR/pops.bed
    done
done

# remove extra file lines except ones starting with numbers (chromosomes), X (for chromosome X), and C (header line)
grep '^[0-9 | X | C]' $OUTPUTDIR/pops.bed > $OUTPUTDIR/neanderthal_introgressed_variants_pops

# sort -k1,1 -k2,2n {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants_sorted.bg
# sort -k1,1 -k2,2n {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/original_deserts.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/original_deserts_sorted.bg

In [ ]:
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants_pops.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants.bg', 
              prefix=False, 
              save_with_header=False)

In [ ]:
# with chr prefix
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants_pops.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants_chr_prefix.bg', 
              prefix=True, 
              save_with_header=False)

In [ ]:
# Make EUR variant files
sankararaman_2016_2 = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants_pops.bed', 
                            sep='\t', low_memory=False)

sankararaman_2016_2['Ancestry'] = sankararaman_2016_2['Population'].apply(tools.map_status)
sankararaman_2016_2_EUR=sankararaman_2016_2[sankararaman_2016_2['Ancestry']=='EUR']

tools.save_bed_only(df=sankararaman_2016_2_EUR, 
         output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants_EUR_chr_prefix.bed', prefix=True)

#### Browning 2018

In [ ]:
tools.browning_2018_raw_to_bed(input_dir=f'{HOMEDIR}/introgression_methods/data/browning_2018',
                               output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018', 
                               output_file_name='neanderthal_introgressed_variants_pops.bed',
                               archaic='Neanderthal',
                               snp_level=True)


tools.browning_2018_raw_to_bed(input_dir=f'{HOMEDIR}/introgression_methods/data/browning_2018',
                               output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering', 
                               output_file_name='neanderthal_introgressed_variants_pops.bed',
                               archaic='Neanderthal',
                               snp_level=True)

Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/neanderthal_introgressed_variants_pops.bed

In [ ]:
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/neanderthal_introgressed_variants_pops.bed', 
        output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/neanderthal_introgressed_variants_chr_prefix.bg', prefix=True)

In [ ]:
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/neanderthal_introgressed_variants_pops.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/neanderthal_introgressed_variants_chr_prefix.bg', 
              prefix=True,
              save_with_header=False)

In [ ]:
# Make EUR variant files
browning_2018 = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018/neanderthal_introgressed_variants_pops.bed', 
                            sep='\t')

browning_2018_EUR=browning_2018[browning_2018['Ancestry']=='EUR']

tools.save_bed_only(df=browning_2018_EUR, 
         output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018/neanderthal_introgressed_variants_EUR_chr_prefix.bed', prefix=True)

In [ ]:
# parse and merge individual files for each population, including papuans
# list files in input_dir
import tarfile
import io
def sort_chromosome(df):
        # define sorting order for 'Chr'
        order = [f'chr{i}' for i in range(1, 23)] + ['chrX', 'chrY']
        # convert 'Chr' to categorical
        df['Chr'] = pd.Categorical(df['Chr'], categories=order, ordered=True)
        # sort by 'Chr' and 'Start'
        df.sort_values(by=['Chr', 'Start'], inplace=True)

def create_fragment_data(df):
        frags = pd.DataFrame(columns = ['Chromosome', 'Start', 'End', 'Population', 'Score'])
        for chrom in df['Chr'].unique().tolist():
            for pop in df['Population'].unique().tolist():
                subset = df[(df['Chr'] == chrom) & (df['Population'] == pop)]
                for segment in subset['Segment_ID'].unique():
                    subset_segment = subset[(subset['Segment_ID'] == segment)]
                    if subset_segment.isna().any().any() == False:
                        start = subset_segment['Start'].min()
                        end = subset_segment['End'].max()
                        frags.loc[len(frags)]=[chrom, start, end, pop, subset_segment['Score'].unique()[0]]
        frags['Method']='Sprime, Browning 2018'
        # add GenomesSource
        frags['GenomesSource']='1KG Phase 3 version 5a'
        # add ScoreName
        frags['ScoreName']='S'
        return frags

input_dir = f'{HOMEDIR}/introgression_methods/data/browning_2018'
files = os.listdir(f'{HOMEDIR}/introgression_methods/data/browning_2018')

dfs = []
for filename in files:
    if filename.endswith('_sprime_results.tar.gz'):
        # extract population name from the filename
        pop = filename.split('_')[0]
        # get path name
        f = input_dir + '/' + filename
        # open tarfile
        tar = tarfile.open(f, 'r:gz')
        # get chromosomal files
        chr_files = [f.name for f in tar.getmembers()]
        # extract chromosomal data
        for chr_file in chr_files:
            contents = tar.extractfile(chr_file).read()
            f = pd.read_csv(io.BytesIO(contents), sep='\t', header=None, skiprows=1)
            # insert population name
            f.insert(5, 'Population', pop)
            # rename chromosome column
            f = f.rename(columns={f.columns[0]:'Chr', 
                            f.columns[1]:'End', 
                            f.columns[2]:'RSID', 
                            f.columns[3]:'Alt',
                            f.columns[4]:'Ref',
                            f.columns[6]:'Segment_ID', 
                            f.columns[8]:'Score',
                            f.columns[9]:'NMatch',
                            f.columns[10]:'DMatch'})
            # keep only rows with 'match' or 'mismatch' in 'NMatch' or 'DMatch' columns (not 'notcomp')
            f = f[(f['NMatch'] != 'notcomp') & (f['DMatch'] != 'notcomp')]
            # keep only segments with at least 30 'match' or 'mismatch' in 'NMatch' and at least 30 for 'DMatch' columns too (not 'notcomp')
            group_by_segment_df = f.groupby('Segment_ID')
            # count number of 'match' or 'mismatch' entries in 'NMatch' and 'DMatch' column for each segment (group)
            nmatch_count_by_group = group_by_segment_df['NMatch'].apply(lambda x: x[x.str.contains('match') | x.str.contains('mismatch')].count())
            dmatch_count_by_group = group_by_segment_df['DMatch'].apply(lambda x: x[x.str.contains('match') | x.str.contains('mismatch')].count())
            # keep segments with at least 30 'match' entries in either column
            segments = group_by_segment_df.filter(lambda x: (nmatch_count_by_group[x.name] >= 30) & (dmatch_count_by_group[x.name] >= 30))
            # compute match rates for each segment: divide number of 'match' entries for the species with the other species as 'mismatch' by the total number of entries
            nean_match_rate = group_by_segment_df.apply(lambda x: ((x['NMatch'] == 'match') & (x['DMatch'] == 'mismatch')).sum() / len(x))
            den_match_rate = group_by_segment_df.apply(lambda x: ((x['DMatch'] == 'match') & (x['NMatch'] == 'mismatch')).sum() / len(x))
            # keep segments with at least 30 'match' entries in either column, plus the match rate criteria
            nean_segments = group_by_segment_df.filter(lambda x: (nmatch_count_by_group[x.name] >= 30) & (dmatch_count_by_group[x.name] >= 30) & (nean_match_rate[x.name] > 0.6) & (den_match_rate[x.name] < 0.4))
            den_segments = group_by_segment_df.filter(lambda x: (nmatch_count_by_group[x.name] >= 30) & (dmatch_count_by_group[x.name] >= 30) & (den_match_rate[x.name] > 0.4) & (nean_match_rate[x.name] < 0.3))
            # append dataframe to list
            dfs.append(nean_segments)

# concatenate dataframes
snps = pd.concat(dfs, ignore_index=True)
# remove rows containing empty Chr values
#snps = snps[~snps['Chr'].isna()]
# sort rows by locus
#snps = snps.sort_values(by=['Chr','End'])
# wrangle dataframe into bed format
#snps = tools.create_bed_format(snps)

In [ ]:
snps = pd.concat(dfs, ignore_index=True)

In [ ]:
snps

,Chr,End,RSID,Alt,Ref,Population,Segment_ID,6,Score,NMatch,DMatch
0,10,753095,rs35927768,T,C,PJL,17,1,404317,match,mismatch
1,10,754487,rs7069720,A,G,PJL,17,1,404317,match,mismatch
2,10,754731,rs12777155,G,C,PJL,17,1,404317,match,mismatch
3,10,755262,rs11253332,G,C,PJL,17,1,404317,match,mismatch
4,10,755932,rs7079450,T,A,PJL,17,1,404317,match,mismatch
...,...,...,...,...,...,...,...,...,...,...,...
752186,9,136742016,rs190255730,C,T,TSI,23,1,350229,mismatch,mismatch
752187,9,136743486,rs184391609,A,G,TSI,23,1,350229,mismatch,mismatch
752188,9,136744999,rs186455536,T,C,TSI,23,1,350229,match,mismatch
752189,9,136757406,rs149026979,G,A,TSI,23,1,350229,mismatch,mismatch
752190,9,136770025,rs530001226,G,T,TSI,23,1,350229,mismatch,mismatch

In [ ]:
papuan_frag_nean = snps[snps['Population']=='Papuans']
papuan_frag_nean['Start'] = papuan_frag_nean['End'] - 1
frags = create_fragment_data(papuan_frag_nean)
frags['length'] = frags['End'] - frags['Start']
frags.length.sum()/1000000

25.45659

In [ ]:
peruvians_frag_nean = snps[snps['Population']=='PEL']
peruvians_frag_nean['Start'] = peruvians_frag_nean['End'] - 1
frags = create_fragment_data(peruvians_frag_nean)
frags['length'] = frags['End'] - frags['Start']
frags.length.sum()/1000000

132.762948

In [ ]:
for pop in snps['Population'].unique():
    pop_subset = snps[snps['Population']==pop]
    pop_subset['Start'] = pop_subset['End'] - 1
    frags = create_fragment_data(pop_subset)
    frags['length'] = frags['End'] - frags['Start']
    print(pop, frags.length.sum()/1000000)

PJL 183.033887
CHS 122.733046
CDX 119.705308
PEL 132.762948
ITU 162.293699
CEU 150.57546
MXL 137.609954
PUR 157.966813
CHB 136.450478
KHV 131.993738
BEB 190.855523
JPT 125.452226
GBR 136.069545
IBS 147.835307
Papuans 25.45659
GIH 162.621503
STU 190.483887
FIN 145.598701
CLM 147.803132
TSI 154.720041

#### Skov 2020

In [ ]:
tools.skov_2020_raw_to_bed(input_file=f'{HOMEDIR}/introgression_methods/data/skov_2020/41586_2020_2225_MOESM4_ESM.txt',
                                output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020', 
                                output_file_name='neanderthal_introgressed_variants_pops.bed',
                                archaic='Neanderthal',
                                snp_level=True,
                                liftover_path='/wynton/group/capra/bin/liftOver')

Reading liftover chains
Mapping coordinates

In [ ]:
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/neanderthal_introgressed_variants_pops.bed', 
        output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/neanderthal_introgressed_variants.bg', prefix=False)

In [ ]:
# with chr prefix
tools.save_bed_only(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/neanderthal_introgressed_variants_pops.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/neanderthal_introgressed_variants_chr_prefix.bg', 
              prefix=True,
              save_with_header=False)

#### Vernot 2016

In [ ]:
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_pops.bed', 
        output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants.bg')

In [ ]:
# with chr prefix
tools.save_bed_only(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_pops.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_chr_prefix.bg', 
              prefix=True,
              save_with_header=False)

In [ ]:
%%bash
# set up directories
HOMEDIR=/wynton/home/capra/ychen39/
INPUTDIR=${HOMEDIR}/introgression_methods/data/vernot_2016/introgressed_tag_snp_frequencies
OUTPUTDIR=${HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/

# for extended LD files
# add data from each population file
for i in ASN EUR PNG SAS; do
    awk -v pop="$i" '{print $1 "\t" $2 "\t" $3 "\t" $4 "\t" pop}' \
    $INPUTDIR/all_tag_snps."$i".merged.ALL.0.3_R2_cluster.1KG_phase3_essentials.bed.extended_LD.sorted >> $OUTPUTDIR/neanderthal_introgressed_variants_pops_extendedLD.bed
done
# sort by chromosome
sort -u $OUTPUTDIR/neanderthal_introgressed_variants_pops_extendedLD.bed | sort -k 1,1 -k2,2n > $OUTPUTDIR/tmp; mv $OUTPUTDIR/tmp $OUTPUTDIR/neanderthal_introgressed_variants_pops_extendedLD.bed
# add column names
sed -i '1s/^/Chromosome\tStart\tStop\tHaplotypeTag\tAncestry\n/' $OUTPUTDIR/neanderthal_introgressed_variants_pops_extendedLD.bed

In [ ]:
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_pops_extendedLD.bed', 
        output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_extendedLD.bg')

In [ ]:
# with chr prefix
tools.save_bed_only(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_pops_extendedLD.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_extendedLD_chr_prefix.bg', 
              prefix=True,
              save_with_header=False)

In [ ]:
%%bash
# set up directories
HOMEDIR=/wynton/home/capra/ychen39/
INPUTDIR=${HOMEDIR}/introgression_methods/data/vernot_2016/introgressed_tag_snp_frequencies
OUTPUTDIR=${HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/

# for median SNPs + extended LD
# add data from each population file
for i in ASN EUR PNG SAS; do
    awk -v pop="$i" '{print $1 "\t" $2 "\t" $3 "\t" $11 "\t" $12 "\t" pop}' \
    $INPUTDIR/all_tag_snps."$i".merged.ALL.0.3_R2_cluster.1KG_phase3_essentials.median_af.bed.extended_LD >> $OUTPUTDIR/neanderthal_introgressed_variants_pops_medianextendedLD.bed
done
# sort by chromosome
sort -u $OUTPUTDIR/neanderthal_introgressed_variants_pops_medianextendedLD.bed | sort -k 1,1 -k2,2n > $OUTPUTDIR/tmp; mv $OUTPUTDIR/tmp $OUTPUTDIR/neanderthal_introgressed_variants_pops_medianextendedLD.bed
# add column names
sed -i '1s/^/Chromosome\tStart\tStop\tSNPsOnHaplotype\tLength\tAncestry\n/' $OUTPUTDIR/neanderthal_introgressed_variants_pops_medianextendedLD.bed

In [ ]:
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_pops_medianextendedLD.bed', 
        output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_medianextendedLD.bg')

In [ ]:
# with chr prefix
tools.save_bed_only(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_pops_medianextendedLD.bed', 
              output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_medianextendedLD_chr_prefix.bg', 
              prefix=True,
              save_with_header=False)

In [ ]:
# Make EUR variant files
vernot_2016 = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_pops.bed', 
                            sep='\t')

vernot_2016_EUR=vernot_2016[vernot_2016['Ancestry']=='EUR']

tools.save_bed_only(df=vernot_2016_EUR, 
         output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_EUR_chr_prefix.bed', prefix=True)

### Skov 2018

In [ ]:
# clean and liftover skov 2018 snp data

tools.skov_2018_raw_to_bed(input_folder=f'{HOMEDIR}/introgression_methods/data/skov_2018', 
                           output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/', 
                           liftover_path='/wynton/group/capra/bin/liftOver', # or /wynton/group/capra/bin/liftOver
                           output_file_name='snps_hg19.bed', 
                           archaic='Neanderthal',
                           snp_level=True)

# save just bed file (no chr prefix)
tools.save_bed_only(full_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/snps_hg19.bed', 
         output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/neanderthal_introgressed_variants.bg', prefix=False)

Cleaning SNP-level data...

Reading liftover chains
Mapping coordinates

### Generate variant overlap file across all methods

In [ ]:
# add column of 1s for a "score" to make proper bedgraphs -- ONLY RUN ONCE

!sed 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/neanderthal_introgressed_variants.bg > \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/neanderthal_introgressed_variants_score.bg
!sed 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants.bg > \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_score.bg
!sed 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_medianextendedLD.bg > \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_medianextendedLD_score.bg
!sed 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_extendedLD.bg > \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_extendedLD_score.bg
!sed 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/neanderthal_introgressed_variants.bg > \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/neanderthal_introgressed_variants_score.bg
!sed 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/neanderthal_introgressed_variants.bg > \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/neanderthal_introgressed_variants_score.bg
!sed 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants.bg > \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants_score.bg
!sed 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/neanderthal_introgressed_variants.bg > \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/neanderthal_introgressed_variants_score.bg
!sed 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/neanderthal_introgressed_variants.bg > \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/neanderthal_introgressed_variants_score.bg

In [ ]:
# bedtools requires '#' to be at the front of each header, but not using a header here
# create union file
!$BEDTOOLSDIR/bedtools unionbedg -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018/neanderthal_introgressed_variants_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_medianextendedLD_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_variants_extendedLD_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/neanderthal_introgressed_variants_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/neanderthal_introgressed_variants_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/neanderthal_introgressed_variants_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/neanderthal_introgressed_variants_score.bg \
    -header -names sprime vernot_2016 vernot_2016_extendedLD vernot_2016_medianextendedLD sankararaman_2014 sankararaman_2016_1 sankararaman_2016_2 skov_2020 skov_2018 > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_variants.bed

In [ ]:
# read in unionbedg file
overlap = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_variants.bed', sep='\t', low_memory=False)
# replace 0s with NA
overlap.replace(0, np.nan, inplace=True)
# add length data
overlap['length'] = overlap['end'] - overlap['start']
# save version with NAs instead of 0s
overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_variants.bed', sep='\t', index=False)

# save bed file version of all identified introgressed segments across methods
overlap[['chrom', 'start', 'end']].to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/overlap_bed_only_variants.bed', sep='\t', index=False)

# first, convert dataframe to boolean values
# exclude for boolean
exclude_columns = ['chrom', 'start', 'end', 'length']
# convert to boolean (exclude columns specified)
boolean_overlap = overlap.copy()
boolean_overlap[boolean_overlap.columns.difference(exclude_columns)] = boolean_overlap[boolean_overlap.columns.difference(exclude_columns)].applymap(lambda x: pd.notna(x))
boolean_overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_variants.bed', sep='\t', index=False)
boolean_overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_no_header_variants.bed', sep='\t', index=False, header=False)

# drop chrom, start, end - used to plot jaccards
boolean_overlap = boolean_overlap.drop(['chrom', 'start', 'end'], axis=1)
boolean_overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_no_bed_variants', sep='\t', index=False)
boolean_overlap

,sprime,vernot_2016,vernot_2016_extendedLD,vernot_2016_medianextendedLD,sankararaman_2014,sankararaman_2016_1,sankararaman_2016_2,skov_2020,skov_2018,length
0,True,False,False,False,False,False,False,False,True,1
1,True,False,False,False,False,False,False,False,True,1
2,False,False,False,False,False,False,False,False,True,1
3,False,False,False,False,False,False,False,False,True,1
4,True,False,False,False,False,False,False,False,True,1
...,...,...,...,...,...,...,...,...,...,...
1645687,False,False,False,False,False,True,False,False,False,1
1645688,False,False,False,False,False,True,False,False,False,1
1645689,False,False,False,False,False,True,False,False,False,1
1645690,False,False,False,False,False,True,False,False,False,1
1645691,False,False,False,False,False,True,False,False,False,1

In [ ]:
# X chrom variants

boolean_overlap_shared_length_highest_scores = tools.generate_overlap(input_files_string=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/neanderthal_introgressed_variants_score_X_only.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/neanderthal_introgressed_variants_score_X_only.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/neanderthal_introgressed_variants_score_X_only.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/neanderthal_introgressed_variants_score_X_only.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/neanderthal_introgressed_variants_score_shuffled_X.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/neanderthal_introgressed_variants_score_shuffled_X.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/neanderthal_introgressed_variants_score_shuffled_X.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/neanderthal_introgressed_variants_score_shuffled_X.bg',
    input_files_names_str='sankararaman_2014 sankararaman_2016_1 sankararaman_2016_2 \
        skov_2020 sankararaman_2014_shuffled \
            sankararaman_2016_1_shuffled sankararaman_2016_2_shuffled skov_2020_shuffled',
    output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_X_variants_with_shuffles.bg',
    boolean=True, autosomes=False)

## Generating standardized fragment files across introgression methods

Here, we use the introgression_tools package to generate standardized individual-level and superpopulation-level introgression data.

Additionally, we will generate "2 Percent" files for individual-level data: we will take the top introgressed regions for each person, consisting of 2% of each individual' genome, so we can repeat individual-level analysis subsetted to "confident" regions and controlling for the same amount of introgression across people.

First, we will convert all raw outputs to standardized .bed and .bg files for later use.

### Skov 2018 (1KG, HGDP)

Introgressed segments were downloaded from https://zenodo.org/records/14136628 (1KG, HGDP).

In [ ]:
!mkdir /wynton/home/capra/ychen39/introgression_methods/data/skov_2018
!wget https://zenodo.org/records/14136628/files/hg38_1000g_segments.txt?download=1 -O /wynton/home/capra/ychen39/introgression_methods/data/skov_2018/hg38_1000g_segments.txt
!wget https://zenodo.org/records/14136628/files/hg38_1000g_SNPS.txt?download=1 -O /wynton/home/capra/ychen39/introgression_methods/data/skov_2018/hg38_1000g_SNPS.txt
!wget https://zenodo.org/records/14136628/files/hg38_HGDP_segments.txt?download=1 -O /wynton/home/capra/ychen39/introgression_methods/data/skov_2018/hg38_HGDP_segments.txt
!wget https://zenodo.org/records/14136628/files/hg38_HGDP_SNPS.txt?download=1 -O /wynton/home/capra/ychen39/introgression_methods/data/skov_2018/hg38_HGDP_SNPS.txt

!mkdir /wynton/home/capra/ychen39/introgression_methods/cleaned/introgression_tools/skov_2018

--2025-11-10 11:47:26--  https://zenodo.org/records/14136628/files/hg38_1000g_SNPS.txt?download=1
Resolving prox1 (prox1)... 172.26.1.6
Connecting to prox1 (prox1)|172.26.1.6|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 30177906 (29M) [text/plain]
Saving to: ‘/wynton/home/capra/ychen39/introgression_methods/data/skov_2018/hg38_1000g_SNPS.txt’

/wynton/home/capra/ 100%[===================>]  28.78M   587KB/s    in 50s

2025-11-10 11:48:16 (594 KB/s) - ‘/wynton/home/capra/ychen39/introgression_methods/data/skov_2018/hg38_1000g_SNPS.txt’ saved [30177906/30177906]

--2025-11-10 11:48:16--  https://zenodo.org/records/14136628/files/hg38_HGDP_segments.txt?download=1
Resolving prox1 (prox1)... 172.26.1.6
Connecting to prox1 (prox1)|172.26.1.6|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 399257886 (381M) [text/plain]
Saving to: ‘/wynton/home/capra/ychen39/introgression_methods/data/skov_2018/hg38_HGDP_segments.txt’

/wynton/home/capra/ 100%[===================>] 380.76M  12.9MB/s    in 76s

2025-11-10 11:49:33 (5.01 MB/s) - ‘/wynton/home/capra/ychen39/introgression_methods/data/skov_2018/hg38_HGDP_segments.txt’ saved [399257886/399257886]

--2025-11-10 11:49:33--  https://zenodo.org/records/14136628/files/hg38_HGDP_SNPS.txt?download=1
Resolving prox1 (prox1)... 172.26.1.6
Connecting to prox1 (prox1)|172.26.1.6|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 34982935 (33M) [text/plain]
Saving to: ‘/wynton/home/capra/ychen39/introgression_methods/data/skov_2018/hg38_HGDP_SNPS.txt’

/wynton/home/capra/ 100%[===================>]  33.36M   618KB/s    in 57s

2025-11-10 11:50:31 (602 KB/s) - ‘/wynton/home/capra/ychen39/introgression_methods/data/skov_2018/hg38_HGDP_SNPS.txt’ saved [34982935/34982935]

In [ ]:
# save fragment files

tools.skov_2018_raw_to_bed(input_folder=f'{HOMEDIR}/introgression_methods/data/skov_2018', 
                           output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/', 
                           liftover_path='/wynton/group/capra/bin/liftOver', # or /wynton/group/capra/bin/liftOver
                           output_file_name='nean_skov2018_frag.bed', 
                           archaic='Neanderthal',
                           individual_level=False,
                           scratch_dir='/scratch/ychen39/')

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/skov_2018//’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/skov_2018//bedgraphs’: File exists

Generating merged bedgraph file for EUR
Generating merged bedgraph file for EAS
Generating merged bedgraph file for AMR
Generating merged bedgraph file for CentralSouthAsia
Generating merged bedgraph file for Oceania
Generating merged bedgraph file for MiddleEast
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/skov_2018//nean_skov2018_frag.bed

In [ ]:
# save individual-level fragment files

tools.skov_2018_raw_to_bed(input_folder=f'{HOMEDIR}/introgression_methods/data/skov_2018', 
                           output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/', 
                           liftover_path='/wynton/group/capra/bin/liftOver', # or /wynton/group/capra/bin/liftOver
                           output_file_name='nean_skov2018_frag.bed', 
                           archaic='Neanderthal',
                           individual_level=True,
                           scratch_dir='/scratch/ychen39/')

# ran this as a shell script bc it took so long --  see skov_2018_data_cleaning in bin folder

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/skov_2018//’: File exists

Generating merged bedgraph file for EUR
Generating merged bedgraph file for EAS
Generating merged bedgraph file for AMR
Generating merged bedgraph file for CentralSouthAsia
Generating merged bedgraph file for Oceania
Generating merged bedgraph file for MiddleEast
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/skov_2018//nean_skov2018_frag.bed

### IBDMix (2020, did not use)

In [ ]:
tools.chen_2020_raw_to_bed(input_path=f'{HOMEDIR}/introgression_methods/data/ibdmix_chen_et_al_2020/Neanderthal sequence in 1000 genome.50kb.txt', 
                           output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/', 
                           output_file_name='individual_nean_chen2020_frag.bed', 
                           individual=True, population=False)

tools.chen_2020_raw_to_bed(input_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/individual_nean_chen2020_frag.bed', 
                           output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/', 
                           output_file_name='superpop_nean_chen2020_frag.bed', 
                           population=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/chen_2020/’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/chen_2020//bedgraphs’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/chen_2020/’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/chen_2020//bedgraphs’: File exists

Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/chen_2020//superpop_nean_chen2020_frag.bed

In [ ]:
tools.chen_2020_raw_to_bed(input_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/individual_nean_chen2020_frag.bed', 
                           output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/', 
                           output_file_name='superpop_nean_chen2020_frag.bed', 
                           population=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/chen_2020/’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/chen_2020//bedgraphs’: File exists

EAS
merged
EUR
merged
AMR
merged
SAS
merged
AFR
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/chen_2020//superpop_nean_chen2020_frag.bed

In [ ]:
# also save separate dataframe with African admixed individuals only
ibdmix = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/ibdmix_chen2020/individual_introgressed_chen2020_frag.bed',
                     sep='\t')
ibdmix_afr_admix = ibdmix[ibdmix.Population.isin(['ACB', 'ASW'])][['Chromosome', 'Start', 'End', 'Score']]
# print the AFR ids
print('IBDMix AFR (including admixed) individuals:', len(ibdmix[ibdmix.Population.isin(['ACB', 'ASW'])].ID.unique()))
ibdmix_afr_admix.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_admix.bed', sep='\t', index=False, header=False)
ibdmix_afr = ibdmix[ibdmix.Population.isin(['LWK', 'GWD', 'MSL', 'YRI', 'ESN'])][['Chromosome', 'Start', 'End', 'Score']]

# print the AFR ids
print('IBDMix AFR (no admixed) individuals:', len(ibdmix[ibdmix.Population.isin(['LWK', 'GWD', 'MSL', 'YRI', 'ESN'])].ID.unique()))

ibdmix_afr.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr.bed', sep='\t', index=False, header=False)


# create merged file
!sort -k1,1 -k2,2n {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_admix.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_admix_sorted.bed
!$BEDTOOLSDIR/bedtools merge -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_admix_sorted.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_admix_merged_sorted.bed
!rm {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_admix.bed {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_admix_sorted.bed

!sort -k1,1 -k2,2n {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_sorted.bed
!$BEDTOOLSDIR/bedtools merge -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_sorted.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_merged_sorted.bed
!rm {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr.bed {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/afr_sorted.bed

In [ ]:
print('IBDMix AFR (no admixed) individuals:', len(ibdmix[ibdmix.Population.isin(['LWK', 'GWD', 'MSL', 'YRI', 'ESN'])].ID.unique()))
print('IBDMix AFR (including admixed) individuals:', len(ibdmix[ibdmix.Population.isin(['ACB', 'ASW'])].ID.unique()) + len(ibdmix[ibdmix.Population.isin(['LWK', 'GWD', 'MSL', 'YRI', 'ESN'])].ID.unique()))

IBDMix AFR (no admixed) individuals: 504
IBDMix AFR (including admixed) individuals: 661

### IBDMix (2024)

In [ ]:
%%bash

# download IBDmix 2024 calls
HOMEDIR='/wynton/home/capra/ychen39/'
#mkdir ${HOMEDIR}/introgression_methods/data/ibdmix_2024
# need to copy file from the "raw" button on github since wget can't handle redirects
# wget https://github.com/PrincetonUniversity/IBDmix/raw/refs/heads/main/IBDmix_calls_using_3_archaics.tar.gz -O ${HOMEDIR}/introgression_methods/data/ibdmix_2024/IBDmix_calls_using_3_archaics.tar.gz

tar -xvzf ${HOMEDIR}/introgression_methods/data/ibdmix_2024/IBDmix_calls_using_3_archaics.tar.gz -C ${HOMEDIR}/introgression_methods/data/ibdmix_2024/

rm ${HOMEDIR}/introgression_methods/data/ibdmix_2024/IBDmix_calls_using_3_archaics.tar.gz

IBDmix_calls_using_3_archaics/
IBDmix_calls_using_3_archaics/README.txt
IBDmix_calls_using_3_archaics/Altai/
IBDmix_calls_using_3_archaics/Altai/ASW.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/ITU.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/PEL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/YRI.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/ACB.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/IBS.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/CHS.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/LWK.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/KHV.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/MSL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/TSI.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/GWD.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/JPT.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/MXL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/PJL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/CHB.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/GIH.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/ESN.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/CLM.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/STU.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/CDX.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/FIN.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/PUR.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/CEU.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/GBR.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Altai/BEB.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/
IBDmix_calls_using_3_archaics/Chagyrskaya/ASW.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/ITU.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/PEL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/YRI.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/ACB.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/IBS.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/CHS.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/LWK.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/KHV.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/MSL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/TSI.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/GWD.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/JPT.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/MXL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/PJL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/CHB.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/GIH.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/ESN.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/CLM.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/STU.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/CDX.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/FIN.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/PUR.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/CEU.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/GBR.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Chagyrskaya/BEB.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/
IBDmix_calls_using_3_archaics/Vindija/ASW.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/ITU.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/PEL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/YRI.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/ACB.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/IBS.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/CHS.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/LWK.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/KHV.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/MSL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/TSI.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/GWD.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/JPT.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/MXL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/PJL.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/CHB.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/GIH.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/ESN.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/CLM.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/STU.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/CDX.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/FIN.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/PUR.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/CEU.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/GBR.0.05cm.lod4.txt
IBDmix_calls_using_3_archaics/Vindija/BEB.0.05cm.lod4.txt
/wynton/home/capra/ychen39/introgression_methods

In [ ]:
# fragment files (individual-level and population-level)
tools.li_2024_raw_to_bed(input_path = f'{HOMEDIR}/introgression_methods/data/ibdmix_2024/IBDmix_calls_using_3_archaics/',
                        output_dir = f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/', 
                        population=True, 
                        individual=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/li_2024/’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/li_2024//bedgraphs’: File exists

Generating merged bedgraph file for AMR
Generating merged bedgraph file for AFR
Generating merged bedgraph file for SAS
Generating merged bedgraph file for EUR
Generating merged bedgraph file for EAS
Generating merged bedgraph file for AdmixedAFR
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/li_2024//ibdmix_2024_introgressed_frag.bg

In [ ]:
ibdmix

,ID,Chromosome,Start,End,Score,cm_dist,pop,Neanderthal_match,Ancestry,ScoreName,IntrogressionSource,Method,GenomesSource
0,HG01257,1,2996560,3015134,9.38817,0.087273,CLM,Altai,AMR,LOD,Neanderthal,"IBDmix, Li 2024",1KG
1,HG01359,1,3011328,3021147,6.84000,0.052065,CLM,Altai,AMR,LOD,Neanderthal,"IBDmix, Li 2024",1KG
2,HG01134,1,3011328,3021147,9.04510,0.052065,CLM,Altai,AMR,LOD,Neanderthal,"IBDmix, Li 2024",1KG
3,HG01345,1,3011328,3021147,9.04510,0.052065,CLM,Altai,AMR,LOD,Neanderthal,"IBDmix, Li 2024",1KG
4,HG01441,1,3011328,3021147,8.74624,0.052065,CLM,Altai,AMR,LOD,Neanderthal,"IBDmix, Li 2024",1KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2677703,NA21098,22,50884883,50928004,4.67420,0.051883,GIH,Vindija,SAS,LOD,Neanderthal,"IBDmix, Li 2024",1KG
2677704,NA21094,22,50928371,50964885,8.90470,0.072192,GIH,Vindija,SAS,LOD,Neanderthal,"IBDmix, Li 2024",1KG
2677705,NA21118,22,50929581,50964885,8.83982,0.066628,GIH,Vindija,SAS,LOD,Neanderthal,"IBDmix, Li 2024",1KG
2677706,NA21133,22,50928009,50964885,9.59587,0.073856,GIH,Vindija,SAS,LOD,Neanderthal,"IBDmix, Li 2024",1KG
2677707,NA21095,22,50987858,51036020,13.58680,0.061276,GIH,Vindija,SAS,LOD,Neanderthal,"IBDmix, Li 2024",1KG

In [ ]:
# also save separate dataframe with African admixed individuals only
ibdmix = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/individual_ibdmix_2024_introgressed_frag.bg',
                     sep='\t')
# rename pop column to Population for consistency
ibdmix.rename(columns={'pop':'Population'}, inplace=True)
ibdmix_afr_admix = ibdmix[ibdmix.Ancestry.isin(['AFR', 'AdmixedAFR'])][['Chromosome', 'Start', 'End', 'Score']]
# print the AFR ids
print('IBDMix AFR (including admixed) individuals:', len(ibdmix[ibdmix.Ancestry.isin(['AFR', 'AdmixedAFR'])].ID.unique()))
ibdmix_afr_admix.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_admix.bed', sep='\t', index=False, header=False)
ibdmix_afr = ibdmix[ibdmix.Population.isin(['LWK', 'GWD', 'MSL', 'YRI', 'ESN'])][['Chromosome', 'Start', 'End', 'Score']]

# print the AFR ids
print('IBDMix AFR (no admixed) individuals:', len(ibdmix[ibdmix.Population.isin(['LWK', 'GWD', 'MSL', 'YRI', 'ESN'])].ID.unique()))

ibdmix_afr.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr.bed', sep='\t', index=False, header=False)


# create merged file
!sort -k1,1 -k2,2n {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_admix.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_admix_sorted.bed
!$BEDTOOLSDIR/bedtools merge -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_admix_sorted.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_with_admix.bg
# add column of 1s for score
!sed -i 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_with_admix.bg
!rm {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_admix.bed {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_admix_sorted.bed

!sort -k1,1 -k2,2n {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_sorted.bed
!$BEDTOOLSDIR/bedtools merge -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_sorted.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_no_admix.bg
# add column of 1s for score
!sed -i 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_no_admix.bg
!rm {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr.bed {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/afr_sorted.bed

IBDMix AFR (including admixed) individuals: 661
IBDMix AFR (no admixed) individuals: 504

In [ ]:
import pandas as pd
ibdmix = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/individual_ibdmix_2024_introgressed_frag.bg',
                     sep='\t')
ibdmix.rename(columns={'pop':'Population'}, inplace=True)

print('IBDMix AFR (no admixed) individuals:', (ibdmix[ibdmix.Population.isin(['LWK', 'GWD', 'MSL', 'YRI', 'ESN'])].ID.unique()))

IBDMix AFR (no admixed) individuals: ['HG03436' 'HG03385' 'HG03439' 'HG03442' 'HG03472' 'HG03063' 'HG03097'
 'HG03225' 'HG03378' 'HG03461' 'HG03556' 'HG03563' 'HG03066' 'HG03073'
 'HG03069' 'HG03571' 'HG03476' 'HG03473' 'HG03548' 'HG03410' 'HG03547'
 'HG03469' 'HG03478' 'HG03074' 'HG03388' 'HG03558' 'HG03565' 'HG03433'
 'HG03577' 'HG03432' 'HG03445' 'HG03428' 'HG03479' 'HG03060' 'HG03572'
 'HG03064' 'HG03078' 'HG03382' 'HG03452' 'HG03559' 'HG03578' 'HG03485'
 'HG03446' 'HG03583' 'HG03061' 'HG03091' 'HG03460' 'HG03455' 'HG03054'
 'HG03055' 'HG03079' 'HG03376' 'HG03084' 'HG03224' 'HG03397' 'HG03464'
 'HG03212' 'HG03451' 'HG03575' 'HG03082' 'HG03052' 'HG03209' 'HG03567'
 'HG03458' 'HG03449' 'HG03484' 'HG03419' 'HG03457' 'HG03077' 'HG03088'
 'HG03057' 'HG03557' 'HG03095' 'HG03096' 'HG03470' 'HG03086' 'HG03391'
 'HG03081' 'HG03394' 'HG03380' 'HG03072' 'HG03058' 'HG03437' 'HG03085'
 'HG03401' 'NA19443' 'NA19037' 'NA19435' 'NA19028' 'NA19428' 'NA19327'
 'NA19462' 'NA19385' 'NA19471' 'NA19390' 'NA19346' 'NA19473' 'NA19378'
 'NA19467' 'NA19376' 'NA19401' 'NA19019' 'NA19355' 'NA19383' 'NA19468'
 'NA19308' 'NA19316' 'NA19331' 'NA19466' 'NA19324' 'NA19380' 'NA19438'
 'NA19374' 'NA19319' 'NA19448' 'NA19027' 'NA19030' 'NA19312' 'NA19309'
 'NA19321' 'NA19384' 'NA19026' 'NA19338' 'NA19307' 'NA19328' 'NA19347'
 'NA19429' 'NA19318' 'NA19379' 'NA19430' 'NA19314' 'NA19036' 'NA19456'
 'NA19020' 'NA19434' 'NA19372' 'NA19377' 'NA19452' 'NA19350' 'NA19375'
 'NA19403' 'NA19391' 'NA19436' 'NA19041' 'NA19472' 'NA19024' 'NA19454'
 'NA19399' 'NA19023' 'NA19320' 'NA19404' 'NA19394' 'NA19439' 'NA19025'
 'NA19440' 'NA19431' 'NA19445' 'NA19474' 'NA19043' 'NA19463' 'NA19042'
 'NA19451' 'NA19446' 'NA19449' 'NA19397' 'NA19317' 'NA19437' 'NA19351'
 'NA19395' 'NA19038' 'NA19475' 'NA19017' 'NA19031' 'NA19457' 'NA19310'
 'NA19323' 'NA19334' 'NA19393' 'NA19035' 'NA19332' 'NA19461' 'NA19455'
 'NA19315' 'NA19360' 'NA18516' 'NA18864' 'NA18915' 'NA18934' 'NA19096'
 'NA19107' 'NA19117' 'NA19137' 'NA19141' 'NA19197' 'NA19257' 'NA18881'
 'NA18508' 'NA18876' 'NA19171' 'NA19222' 'NA19223' 'NA19247' 'NA19207'
 'NA19200' 'NA19204' 'NA19144' 'NA18878' 'NA19146' 'NA18489' 'NA19095'
 'NA18505' 'NA18523' 'NA19108' 'NA19236' 'NA18867' 'NA18511' 'NA19248'
 'NA18924' 'NA19147' 'NA19143' 'NA18879' 'NA19130' 'NA19131' 'NA19213'
 'NA18499' 'NA18923' 'NA19256' 'NA19092' 'NA18501' 'NA19189' 'NA18868'
 'NA18871' 'NA19121' 'NA19206' 'NA18908' 'NA18520' 'NA19114' 'NA19093'
 'NA19152' 'NA19153' 'NA19209' 'NA18853' 'NA19113' 'NA18502' 'NA18907'
 'NA19225' 'NA18909' 'NA18933' 'NA19119' 'NA18488' 'NA19129' 'NA18510'
 'NA18865' 'NA18874' 'NA19175' 'NA19184' 'NA19235' 'NA19138' 'NA18910'
 'NA19201' 'NA19160' 'NA19239' 'NA18917' 'NA18856' 'NA18858' 'NA18861'
 'NA19099' 'NA19118' 'NA19149' 'NA18504' 'NA19098' 'NA18877' 'NA18916'
 'NA19172' 'NA18498' 'NA19210' 'NA19185' 'NA19190' 'NA19198' 'NA18486'
 'NA18519' 'NA19238' 'NA19214' 'NA19102' 'NA19116' 'NA19159' 'NA18870'
 'NA18912' 'NA18507' 'NA18873' 'NA18517' 'NA18522' 'HG03045' 'HG03046'
 'HG02840' 'HG02861' 'HG02679' 'HG02716' 'HG02879' 'HG02881' 'HG02860'
 'HG02570' 'HG02571' 'HG02678' 'HG02588' 'HG02805' 'HG02813' 'HG03539'
 'HG03025' 'HG03258' 'HG02611' 'HG02763' 'HG02852' 'HG02722' 'HG02715'
 'HG02623' 'HG02870' 'HG03240' 'HG02620' 'HG02629' 'HG02643' 'HG02768'
 'HG02816' 'HG02887' 'HG03024' 'HG02811' 'HG02589' 'HG02896' 'HG02771'
 'HG02594' 'HG02882' 'HG03241' 'HG02585' 'HG02807' 'HG02820' 'HG03048'
 'HG02586' 'HG02839' 'HG02851' 'HG02855' 'HG02837' 'HG02582' 'HG03259'
 'HG03246' 'HG02621' 'HG02819' 'HG02888' 'HG02461' 'HG02464' 'HG02635'
 'HG02760' 'HG02628' 'HG02769' 'HG02574' 'HG02573' 'HG02895' 'HG02891'
 'HG03027' 'HG02666' 'HG02462' 'HG02878' 'HG02702' 'HG02983' 'HG02676'
 'HG02982' 'HG02703' 'HG02624' 'HG02721' 'HG02595' 'HG02836' 'HG02814'
 'HG02890' 'HG02884' 'HG02645' 'HG02798' 'HG02808' 'HG02804' 'HG03247'
 'HG02854' 'HG02756' 'HG02757' 'HG02562' 'HG02759' 'HG02613' 'HG02465'
 'HG02646' 'HG02583' 'HG02885' 'HG02568' 'HG02561' 'HG02799' 'HG02675'
 'HG03039' 'HG03040' 'HG02667' 'HG03049' 'HG02610' 'HG02772' 'HG03538'
 'HG02810' 'HG02634' 'HG02817' 'HG03028' 'HG02614' 'HG02642' 'HG03133'
 'HG02922' 'HG03162' 'HG03166' 'HG03199' 'HG03291' 'HG03303' 'HG03099'
 'HG03202' 'HG02970' 'HG03163' 'HG03351' 'HG03499' 'HG02979' 'HG03297'
 'HG03112' 'HG03372' 'HG03120' 'HG02981' 'HG02946' 'HG02973' 'HG02944'
 'HG03271' 'HG03367' 'HG03270' 'HG03124' 'HG03352' 'HG02971' 'HG03111'
 'HG03370' 'HG03514' 'HG03294' 'HG03168' 'HG02976' 'HG03198' 'HG03343'
 'HG03354' 'HG03521' 'HG03130' 'HG03369' 'HG03126' 'HG03103' 'HG03115'
 'HG03363' 'HG02947' 'HG03267' 'HG03114' 'HG03129' 'HG03109' 'HG03100'
 'HG03105' 'HG03135' 'HG03313' 'HG03175' 'HG02941' 'HG03268' 'HG02953'
 'HG03108' 'HG03127' 'HG03265' 'HG03295' 'HG03517' 'HG03518' 'HG03366'
 'HG03132' 'HG03139' 'HG02974' 'HG03159' 'HG03311' 'HG03515' 'HG03136'
 'HG03511' 'HG03123' 'HG03279' 'HG02968' 'HG02938' 'HG03121' 'HG03190'
 'HG02923' 'HG03189' 'HG03195' 'HG03118' 'HG02943' 'HG03157' 'HG03301'
 'HG03196' 'HG03342' 'HG03172' 'HG02952' 'HG03298' 'HG03300' 'HG02977'
 'HG03117' 'HG03304' 'HG03520' 'HG03193' 'HG03280' 'HG03160' 'HG03169']

In [ ]:
print('IBDMix AFR (no admixed) individuals:', len(ibdmix[ibdmix.Population.isin(['LWK', 'GWD', 'MSL', 'YRI', 'ESN'])].ID.unique()))
print('IBDMix AFR (including admixed) individuals:', len(ibdmix[ibdmix.Population.isin(['ACB', 'ASW'])].ID.unique()) + len(ibdmix[ibdmix.Population.isin(['LWK', 'GWD', 'MSL', 'YRI', 'ESN'])].ID.unique()))

IBDMix AFR (no admixed) individuals: 504
IBDMix AFR (including admixed) individuals: 661

In [ ]:
ibdmix['Ancestry'].unique()

array(['AMR', 'AFR', 'SAS', 'EUR', 'EAS', 'AdmixedAFR'], dtype=object)

### ArchaicSeeker2

In [ ]:
tools.yuan_2021_raw_to_bed(input_dir_list=[f'{HOMEDIR}/introgression_methods/data/archaicseeker2.0_yuan_et_al_2021/IntrogressedSeg/KGP/EastAsia', 
                                       f'{HOMEDIR}/introgression_methods/data/archaicseeker2.0_yuan_et_al_2021/IntrogressedSeg/KGP/SouthAsia', 
                                       f'{HOMEDIR}/introgression_methods/data/archaicseeker2.0_yuan_et_al_2021/IntrogressedSeg/KGP/WestEurasia',
                                       f'{HOMEDIR}/introgression_methods/data/archaicseeker2.0_yuan_et_al_2021/IntrogressedSeg/SGDP'],
                           output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021', 
                           output_file_name='individual_nean_yuan2021_frag.bed', 
                           archaic='Neanderthal',
                           individual=True)

tools.yuan_2021_raw_to_bed(file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/individual_nean_yuan2021_frag.bed',
                           output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/', 
                           output_file_name='superpop_nean_yuan2021_frag.bed', 
                           archaic='Neanderthal',
                           population=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/yuan_2021’: File exists
/wynton/home/capra/ychen39/.conda/envs/jupyter/lib/python3.11/site-packages/pyranges/methods/init.py:45: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return {k: v for k, v in df.groupby(grpby_key)}
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/yuan_2021//bedgraphs’: File exists

EAS
merged
SAS
merged
EUR
merged
Oceania
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/yuan_2021//superpop_nean_yuan2021_frag.bed

In [ ]:
## retry, removed "contains" to exact match for "Neanderthal" and "Denisovan"

tools.yuan_2021_raw_to_bed(input_dir_list=[f'{HOMEDIR}/introgression_methods/data/archaicseeker2.0_yuan_et_al_2021/IntrogressedSeg/KGP/EastAsia', 
                                       f'{HOMEDIR}/introgression_methods/data/archaicseeker2.0_yuan_et_al_2021/IntrogressedSeg/KGP/SouthAsia', 
                                       f'{HOMEDIR}/introgression_methods/data/archaicseeker2.0_yuan_et_al_2021/IntrogressedSeg/KGP/WestEurasia',
                                       f'{HOMEDIR}/introgression_methods/data/archaicseeker2.0_yuan_et_al_2021/IntrogressedSeg/SGDP'],
                           output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/debugging/', 
                           output_file_name='individual_nean_yuan2021_frag.bed', 
                           archaic='Neanderthal',
                           individual=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/yuan_2021/debugging/’: File exists
/wynton/home/capra/ychen39/.conda/envs/jupyter/lib/python3.11/site-packages/pyranges/methods/init.py:45: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return {k: v for k, v in df.groupby(grpby_key)}

### ArchIE

In [ ]:
# using an increased threshold so we get ~2% introgression per person
tools.durvasula_2019_raw_to_bed(input_dir=f'{HOMEDIR}/introgression_methods/data/archie_durvasula2019/CEU-predictions',
                                ancestry='EUR',
                                output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019', 
                                output_file_name='individual_nean_durvasula2019_frag_higher_threshold.bed', 
                                individual=True,
                                threshold=0.9984,
                                keep_old_score=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/durvasula_2019’: File exists

Reading CEU.chr22-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr6-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr15-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr8-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr10-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr12-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr21-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr19-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr9-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr17-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr18-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr7-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr2-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr3-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr20-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr4-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr16-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr1-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr14-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr5-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr11-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr13-prediction.bed.gz-trimmed.bed.gz

In [ ]:
# using the threshold reported in the paper
tools.durvasula_2019_raw_to_bed(input_dir=f'{HOMEDIR}/introgression_methods/data/archie_durvasula2019/CEU-predictions',
                                ancestry='EUR',
                                output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019', 
                                output_file_name='individual_nean_durvasula2019_frag_thresholded_0.862.bed', 
                                individual=True,
                                threshold=0.862,
                                keep_old_score=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/durvasula_2019’: File exists

Reading CEU.chr22-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr6-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr15-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr8-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr10-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr12-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr21-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr19-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr9-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr17-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr18-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr7-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr2-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr3-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr20-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr4-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr16-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr1-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr14-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr5-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr11-prediction.bed.gz-trimmed.bed.gz
Reading CEU.chr13-prediction.bed.gz-trimmed.bed.gz

In [ ]:
tools.durvasula_2019_raw_to_bed(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019',
                                ancestry='EUR',
                                file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/individual_nean_durvasula2019_frag_higher_threshold.bed',
                                output_file_name='superpop_nean_durvasula2019_frag.bed', 
                                population=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/durvasula_2019’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs’: File exists

EUR
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/durvasula_2019/superpop_nean_durvasula2019_frag.bed

cp: target 'union_merged.bg' is not a directory

In [ ]:
tools.durvasula_2019_raw_to_bed(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019',
                                ancestry='EUR',
                                file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/individual_nean_durvasula2019_frag.bed',
                                output_file_name='superpop_nean_durvasula2019_frag_thresholded_0.862.bed', 
                                population=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/durvasula_2019’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs’: File exists

EUR
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/durvasula_2019/superpop_nean_durvasula2019_frag_thresholded_0.862.bed

### DICAL-ADMIX

In [ ]:
#tools.steinruecken_2018_raw_to_bed(input_dir=f'{HOMEDIR}/introgression_methods/data/steinrucken_2018/called_tracts',
                                # output_dir=f'{HOMEDIR}/introgression_methods/introgression_tools/test/dicaladmix/', 
                                # output_file_name='individual_nean_introgressed_steinrucken2018_frag.bed',
                                # prob_dir= f'{HOMEDIR}/introgression_methods/data/dical-steinrucken_2018/posterior_probabilities',
                                # input_tar_gz='CEU_lax_chr1_beds.tar.gz',
                                # individual=True) 
# 
## did not run this, used bash script instead (clean_steinrucken_parallel_round2). 
## already generated individual=level file with posterior probabilities

IndentationError: unexpected indent (1665664957.py, line 2)

In [ ]:
tools.steinruecken_2018_raw_to_bed(file_path=f'{HOMEDIR}/introgression_methods/cleaned/steinruecken_2018/individual_introgressed_steinruecken2018_frag.bed',
                                output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018', 
                                output_file_name='superpop_nean_steinruecken2018_frag.bed',
                                population=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/steinruecken_2018/’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs’: File exists

CEU
merged
CHBS
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/steinruecken_2018/superpop_nean_steinruecken2018_frag.bed

### Skov2020

In [ ]:
tools.skov_2020_raw_to_bed(input_file=f'{HOMEDIR}/introgression_methods/data/skov_2020/hg38_to_hg19_liftover/skov_2020_lifted.bed',
                                output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020', 
                                output_file_name='superpop_nean_skov2020_frag.bed',
                                population=True,
                                archaic='Neanderthal')

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/skov_2020/’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs’: File exists

Icelandic
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/skov_2020/superpop_nean_skov2020_frag.bed

In [ ]:
# also clean variants file
#awk '{print $1,$2,$2+1}' {HOMEDIR}/introgression_methods/data/skov_2020/41586_2020_2225_MOESM4_ESM.txt > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/snps.bed

skov_2020_variants = pd.read_csv(f'{HOMEDIR}/introgression_methods/data/skov_2020/41586_2020_2225_MOESM4_ESM.txt', sep='\t', low_memory=False)
# add end position
skov_2020_variants['start'] = skov_2020_variants['pos'] - 1
#print(skov_2020_variants.snptype.unique())
# keep only DAV snps
skov_2020_variants = skov_2020_variants[(skov_2020_variants['snptype'] == 'DAVsnp') | (skov_2020_variants['snptype'] == 'linkedDAVsnp')]
# rename pos to end
skov_2020_variants.rename(columns={'pos': 'end'}, inplace=True)
# keep only bed positions
skov_2020_variants_bed = skov_2020_variants[['chrom', 'start', 'end']]
skov_2020_variants_bed
# save to file -- version with chr prefix for liftover
skov_2020_variants_bed.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/dav_and_linked_snps_hg38_chr_prefix.bg', header=False, sep='\t', index=False)
#drop 'chr' prefix
skov_2020_variants_bed['chrom'] = skov_2020_variants_bed['chrom'].str.replace('chr', '')
# save to file
skov_2020_variants_bed.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/dav_and_linked_snps_hg38.bg', header=False, sep='\t', index=False)

### SARGE

In [ ]:
sarge = pd.read_csv(f'{HOMEDIR}/introgression_methods/data/sarge_schaefer2021/sarge_admixed_haps_hs37d5.bed', sep='\t')
len(sarge['hap'][sarge['pop'] == 'Africa'].unique()) / 2

32.0

In [ ]:
tools.schaefer_2021_raw_to_bed(input_file=f'{HOMEDIR}/introgression_methods/data/sarge_schaefer2021/sarge_admixed_haps_hs37d5.bed',
                                output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/', 
                                output_file_name='individual_nean_schaefer2021_frag.bed',
                                individual=True,
                                archaic='Neanderthal')

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/schaefer_2021/’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/schaefer_2021//bedgraphs’: File exists

In [ ]:
tools.schaefer_2021_raw_to_bed(input_file=f'{HOMEDIR}/introgression_methods/data/sarge_schaefer2021/sarge_admixed_haps_hs37d5.bed',
                                output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/', 
                                output_file_name='superpop_nean_schaefer2021_frag.bed',
                                population=True,
                                archaic='Neanderthal')

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/schaefer_2021/’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/schaefer_2021//bedgraphs’: File exists

Oceania
merged
WestEurasia
merged
EastAsia
merged
Africa
merged
Africa2
merged
America
merged
CentralAsiaSiberia
merged
SouthAsia
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/schaefer_2021//superpop_nean_schaefer2021_frag.bed

In [ ]:
# get IDs in Africa vs Africa2
sarge = pd.read_csv(f'{HOMEDIR}/introgression_methods/data/sarge_schaefer2021/sarge_admixed_haps_hs37d5.bed', sep='\t')
afr_ids = sarge['hap'][(sarge['pop'] == 'Africa') | (sarge['pop'] == 'Africa2')].unique()
afr2_ids = sarge['hap'][sarge['pop'] == 'Africa2'].unique()
print('Number of AFR IDs:', len(afr_ids))
print('Number of AFR2 IDs:', len(afr2_ids))

Number of AFR IDs: 88

In [ ]:
# save to file
afr_ids

array(['B_Dinka-3-1', 'B_Dinka-3-2', 'B_Ju_hoan_North-4-1',
       'B_Ju_hoan_North-4-2', 'B_Mandenka-3-1', 'B_Mandenka-3-2',
       'B_Mbuti-4-1', 'B_Mbuti-4-2', 'B_Yoruba-3-1', 'B_Yoruba-3-2',
       'S_BantuHerero-1-1', 'S_BantuHerero-1-2', 'S_BantuHerero-2-1',
       'S_BantuHerero-2-2', 'S_BantuKenya-1-1', 'S_BantuKenya-1-2',
       'S_BantuKenya-2-1', 'S_BantuKenya-2-2', 'S_BantuTswana-1-1',
       'S_BantuTswana-1-2', 'S_BantuTswana-2-1', 'S_BantuTswana-2-2',
       'S_Biaka-1-1', 'S_Biaka-1-2', 'S_Biaka-2-1', 'S_Biaka-2-2',
       'S_Dinka-1-1', 'S_Dinka-1-2', 'S_Dinka-2-1', 'S_Dinka-2-2',
       'S_Esan-1-1', 'S_Esan-1-2', 'S_Esan-2-1', 'S_Esan-2-2',
       'S_Gambian-1-1', 'S_Gambian-1-2', 'S_Gambian-2-1', 'S_Gambian-2-2',
       'S_Ju_hoan_North-1-1', 'S_Ju_hoan_North-1-2',
       'S_Ju_hoan_North-2-1', 'S_Ju_hoan_North-2-2',
       'S_Ju_hoan_North-3-1', 'S_Ju_hoan_North-3-2', 'S_Khomani_San-1-1',
       'S_Khomani_San-1-2', 'S_Khomani_San-2-1', 'S_Khomani_San-2-2',
       'S_Luhya-1-1', 'S_Luhya-1-2', 'S_Luhya-2-1', 'S_Luhya-2-2',
       'S_Luo-1-1', 'S_Luo-1-2', 'S_Luo-2-1', 'S_Luo-2-2',
       'S_Mandenka-1-1', 'S_Mandenka-1-2', 'S_Mandenka-2-1',
       'S_Mandenka-2-2', 'S_Masai-1-1', 'S_Masai-1-2', 'S_Masai-2-1',
       'S_Masai-2-2', 'S_Mbuti-1-1', 'S_Mbuti-1-2', 'S_Mbuti-2-1',
       'S_Mbuti-2-2', 'S_Mbuti-3-1', 'S_Mbuti-3-2', 'S_Mende-1-1',
       'S_Mende-1-2', 'S_Mende-2-1', 'S_Mende-2-2', 'S_Mozabite-1-1',
       'S_Mozabite-1-2', 'S_Mozabite-2-1', 'S_Mozabite-2-2',
       'S_Saharawi-1-1', 'S_Saharawi-1-2', 'S_Saharawi-2-1',
       'S_Saharawi-2-2', 'S_Somali-1-1', 'S_Somali-1-2', 'S_Yoruba-1-1',
       'S_Yoruba-1-2', 'S_Yoruba-2-1', 'S_Yoruba-2-2'], dtype=object)

In [ ]:
afr2_ids # no admixed, most diverged

array(['B_Ju_hoan_North-4-1', 'B_Ju_hoan_North-4-2', 'B_Mbuti-4-1',
       'B_Mbuti-4-2', 'S_Biaka-1-1', 'S_Biaka-1-2', 'S_Biaka-2-1',
       'S_Biaka-2-2', 'S_Ju_hoan_North-1-1', 'S_Ju_hoan_North-1-2',
       'S_Ju_hoan_North-2-1', 'S_Ju_hoan_North-2-2',
       'S_Ju_hoan_North-3-1', 'S_Ju_hoan_North-3-2', 'S_Khomani_San-1-1',
       'S_Khomani_San-1-2', 'S_Khomani_San-2-1', 'S_Khomani_San-2-2',
       'S_Mbuti-1-1', 'S_Mbuti-1-2', 'S_Mbuti-2-1', 'S_Mbuti-2-2',
       'S_Mbuti-3-1', 'S_Mbuti-3-2'], dtype=object)

### ARGWeaver-D

In [ ]:
## Process individual files first
tools.hubisz_2020_raw_to_bed(input_path=f'{HOMEDIR}/introgression_methods/data/argweaver-d_hubisz_et_al_2020/ooaM1A/Mandenka_2F.bed', 
                               ancestry='Africa', 
                               ID='LP6005441-DNA_F07',
                               archaic='Neanderthal',
                               output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020',
                               output_file_name='mandenka_individual_nean_hubisz2020_frag.bed',
                               individual=True)

tools.hubisz_2020_raw_to_bed(input_path=f'{HOMEDIR}/introgression_methods/data/argweaver-d_hubisz_et_al_2020/ooaM1A/Papuan_1F.bed', 
                               ancestry='Oceania', 
                               ID='LP6005441-DNA_B10',
                               archaic='Neanderthal',
                               output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020',
                               output_file_name='papuan_individual_nean_hubisz2020_frag.bed',
                               individual=True)

tools.hubisz_2020_raw_to_bed(input_path=f'{HOMEDIR}/introgression_methods/data/argweaver-d_hubisz_et_al_2020/ooaM1A/Khomani_San_1F.bed', 
                               ancestry='Africa', 
                               ID='LP6005677-DNA_D03',
                               archaic='Neanderthal',
                               output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020',
                               output_file_name='khomani_san_individual_nean_hubisz2020_frag.bed',
                               individual=True)

tools.hubisz_2020_raw_to_bed(input_path=f'{HOMEDIR}/introgression_methods/data/argweaver-d_hubisz_et_al_2020/ooaM1A/Basque_2F.bed', 
                               ancestry='WestEurasia', 
                               ID='LP6005441-DNA_D02',
                               archaic='Neanderthal',
                               output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020',
                               output_file_name='basque_individual_nean_hubisz2020_frag.bed',
                               individual=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020’: File exists

Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020/mandenka_individual_nean_hubisz2020_frag.bed
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020/papuan_individual_nean_hubisz2020_frag.bed
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020/khomani_san_individual_nean_hubisz2020_frag.bed
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020/basque_individual_nean_hubisz2020_frag.bed

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs’: File exists

Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020/superpop_nean_hubisz2020_frag.bed

In [ ]:
## Process population files, concatenate
tools.hubisz_2020_raw_to_bed(individual_files=[f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/mandenka_individual_nean_hubisz2020_frag.bed',
                                               f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/papuan_individual_nean_hubisz2020_frag.bed',
                                               f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/khomani_san_individual_nean_hubisz2020_frag.bed',
                                               f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/basque_individual_nean_hubisz2020_frag.bed'], 
                               output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020',
                               output_file_name='superpop_nean_hubisz2020_frag.bed',
                               population=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs’: File exists

Africa
merged
Oceania
merged
WestEurasia
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/hubisz_2020/superpop_nean_hubisz2020_frag.bed

### Sprime

In [ ]:
# tools.browning_2018_raw_to_bed(input_dir=f'{HOMEDIR}/introgression_methods/data/browning_2018',
#                                output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018', 
#                                output_file_name='superpop_nean_browning2018_frag.bed',
#                                archaic='Neanderthal')

tools.browning_2018_raw_to_bed(input_dir=f'{HOMEDIR}/introgression_methods/data/browning_2018',
                               output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering', 
                               output_file_name='superpop_nean_browning2018_frag.bed',
                               archaic='Neanderthal')

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering’: File exists

chr1
chr2
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr20
chr21
chr22
Generating merged bedgraph file for EAS
Generating merged bedgraph file for AMR
Generating merged bedgraph file for EUR
Generating merged bedgraph file for SAS
Generating merged bedgraph file for Oceania
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/superpop_nean_browning2018_frag.bed

### S*

In [ ]:
%%bash

# set up directories
HOMEDIR=/wynton/home/capra/ychen39/
INPUTDIR=${HOMEDIR}/introgression_methods/data/vernot_2016/introgressed_haplotypes
OUTPUTDIR=${HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/vernot_2016_round2

# for neanderthal
# add data from each population file
for i in EAS EUR PNG SAS; do
    awk -v pop="$i" '{print $1 "\t" $2 "\t" $3 "\t" $5 "\t" pop}' \
    $INPUTDIR/LL.callset"$i".mr_0.99.neand_calls_by_hap.bed.merged.by_chr.bed >> $OUTPUTDIR/neanderthal_introgressed_haplotypes_individual.bed
done

# for denisovan
# add data from each population file
for i in PNG; do
    awk -v pop="$i" '{print $1 "\t" $2 "\t" $3 "\t" $5 "\t" pop}' \
    $INPUTDIR/LL.callset"$i".mr_0.99.den_calls_by_hap.bed.merged.by_chr.bed >> $OUTPUTDIR/denisovan_introgressed_haplotypes_individual.bed # correct number of snps, should be 526,225
done

# sort by chromosome
sort -u $OUTPUTDIR/neanderthal_introgressed_haplotypes_individual.bed | sort -k 1,1 -k2,2n > $OUTPUTDIR/tmp; mv $OUTPUTDIR/tmp $OUTPUTDIR/neanderthal_introgressed_haplotypes_individual.bed
sort -u $OUTPUTDIR/denisovan_introgressed_haplotypes_individual.bed | sort -k 1,1 -k2,2n > $OUTPUTDIR/tmp; mv $OUTPUTDIR/tmp $OUTPUTDIR/denisovan_introgressed_haplotypes_individual.bed

In [ ]:
tools.vernot_2016_raw_to_bed(raw_introgressed_haplotypes_dir=f'{HOMEDIR}/introgression_methods/data/vernot_2016/introgressed_haplotypes',
    introgressed_haplotypes_file=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_haplotypes_individual.bed', 
                             output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/', 
                             output_file_name='neanderthal_introgressed_haplotypes_individual.bed',
                             archaic='Neanderthal', individual_level=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/vernot_2016//tmp/’: File exists

In [ ]:
tools.vernot_2016_raw_to_bed(raw_introgressed_haplotypes_dir=f'{HOMEDIR}/introgression_methods/data/vernot_2016/introgressed_haplotypes',
                             introgressed_haplotypes_file=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_haplotypes_individual.bed', 
                             output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/', 
                             output_file_name='superpop_nean_vernot2016_frag.bed',
                             archaic='Neanderthal')

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/vernot_2016/’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/vernot_2016//bedgraphs’: File exists

EAS
merged
SAS
merged
EUR
merged
PNG
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/vernot_2016//superpop_nean_vernot2016_frag.bed

In [ ]:
tools.vernot_2016_raw_to_bed_snp(snp_input_file=f'{HOMEDIR}/introgression_methods/cleaned/vernot_2016/ancestral_introgressed_variants.bed', 
                             extended_ld_input_file=f'{HOMEDIR}/introgression_methods/cleaned/vernot_2016/ancestral_introgressed_variants_extendedLD.bed', 
                             hap_input_file=f'{HOMEDIR}/introgression_methods/cleaned/vernot_2016/ancestral_introgressed_variants_medianextendedLD.bed', 
                             output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/', 
                             output_file_name='superpop_nean_vernot2016_frag_round2.bed',
                             archaic='Neanderthal') # fixed exact match for derived/archaic alleles, changed to isin

In [ ]:
tools.vernot_2016_raw_to_bed_snp(snp_input_file=f'{HOMEDIR}/introgression_methods/cleaned/vernot_2016/ancestral_introgressed_variants.bed', 
                             extended_ld_input_file=f'{HOMEDIR}/introgression_methods/cleaned/vernot_2016/ancestral_introgressed_variants_extendedLD.bed', 
                             hap_input_file=f'{HOMEDIR}/introgression_methods/cleaned/vernot_2016/ancestral_introgressed_variants_medianextendedLD.bed', 
                             output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/denisovan', 
                             output_file_name='superpop_den_vernot2016_frag_round2.bed',
                             archaic='Denisovan') # fixed exact match for derived/archaic alleles, changed to isin

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/vernot_2016/vernot_2016_round2/denisovan’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/vernot_2016/vernot_2016_round2/denisovan/bedgraphs’: File exists

SAS
merged
ASN
merged
PNG
merged
EUR
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/vernot_2016/vernot_2016_round2/denisovan/superpop_den_vernot2016_frag_round2.bed

### CRF 2014

In [ ]:
tools.sankararaman_2014_raw_to_bed(snp_input_file=f'{HOMEDIR}/introgression_methods/cleaned/sankararaman_2014_copy/neanderthal_introgressed_variants_pops.bed', 
                             hap_input_file=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/1kgids_individual_neanderthal_introgressed_fragments_pops.bed', 
                             output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014', 
                             output_file_name='superpop_nean_sankararaman2014_frag.bed')

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/sankararaman_2014’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs’: File exists

EUR
merged
EAS
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/sankararaman_2014/superpop_nean_sankararaman2014_frag.bed

### CRF 2016

In [ ]:
tools.sankararaman_2016_raw_to_bed(hap_input_file=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/sgdp_individual_neanderthal_introgressed_fragments_pops.bed', 
                             output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1', 
                             output_file_name='superpop_nean_sankararaman2016_1_frag.bed')

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/sankararaman_2016_1’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs’: File exists

AMR
merged
CentralAsia
merged
EAS
merged
Oceania
merged
SAS
merged
EUR
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/superpop_nean_sankararaman2016_1_frag.bed

In [ ]:
tools.sankararaman_2016_raw_to_bed(hap_input_file=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/sgdp_individual_neanderthal_introgressed_fragments_pops.bed', 
                             output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2', 
                             output_file_name='superpop_nean_sankararaman2016_2_frag.bed')

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/sankararaman_2016_2’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs’: File exists

AMR
merged
CentralAsia
merged
EAS
merged
Oceania
merged
SAS
merged
EUR
merged
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/superpop_nean_sankararaman2016_2_frag.bed

### Admixfrog (Iasi 2024)

In [ ]:
%%bash

# download data
HOMEDIR='/wynton/home/capra/ychen39/'
# mkdir ${HOMEDIR}/introgression_methods/data/admixfrog_2025
# wget https://datadryad.org/downloads/file_stream/3666784 -O ${HOMEDIR}/introgression_methods/data/admixfrog_2025/ALL_called_ancestry_segments.csv.zip # didn't work, downloaded locally and copied over
# also download meta data file

unzip ${HOMEDIR}/introgression_methods/data/admixfrog_2025/ALL_called_ancestry_segments.csv.zip -d ${HOMEDIR}/introgression_methods/data/admixfrog_2025/

#rm ${HOMEDIR}/introgression_methods/data/admixfrog_2025/ALL_called_ancestry_segments.csv.zip

Archive:  /wynton/home/capra/ychen39//introgression_methods/data/admixfrog_2025/ALL_called_ancestry_segments.csv.zip
  inflating: /wynton/home/capra/ychen39//introgression_methods/data/admixfrog_2025/ALL_called_ancestry_segments_updated_3rdDec_2025.csv

In [ ]:
df = pd.read_csv(f'{HOMEDIR}/introgression_methods/data/admixfrog_2025/ALL_called_ancestry_segments_updated_3rdDec_2025.csv', sep=',', low_memory=False)
metadata_df = pd.read_csv(f'{HOMEDIR}/introgression_methods/data/admixfrog_2025/Meta_Data_individuals.csv', sep=',', low_memory=False)
df = df[df['type'] == 'state']
df = df[df['target'] == 'NEA']
df = df[df['map_len'] > 0.05]
df = df[df['genetic_map'] == 'Shared_map']

metadata_df = pd.read_csv(f'{HOMEDIR}/introgression_methods/data/admixfrog_2025/Meta_Data_individuals.csv', sep=',', low_memory=False)
metadata_df = metadata_df[['sample_name', 'pop', 'superpopulation', 'time']]
# replace . with - in sample_name to match df
metadata_df['sample_name'] = metadata_df['sample_name'].str.replace('.', '-')
# merge metadata with df
merged_df = pd.merge(df, metadata_df, left_on='sample', right_on='sample_name', how='left')
merged_df = merged_df[merged_df['time'] == 'present']

/scratch/ychen39/ipykernel_946079/1210252709.py:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  metadata_df['sample_name'] = metadata_df['sample_name'].str.replace('.', '-')

In [ ]:
len_segments = []
num_segments = []
ceu_1kg = merged_df[merged_df['superpopulation'] == 'WEurAs']
for sample_id in ceu_1kg['sample'].unique():
    individual_df = ceu_1kg[ceu_1kg['sample'] == sample_id]
    individual_df['chrom'] = 'chr' + individual_df['chrom']
    individual_bed = pybedtools.BedTool.from_dataframe(individual_df[['chrom', 'pos', 'pos_end']])
    individual_bed = individual_bed.sort().merge().to_dataframe()
    individual_bed['length'] = individual_bed['end'] - individual_bed['start']
    total_length = len(individual_bed)
    num_segments.append(total_length)
    len_segments.append(np.mean(individual_bed['length']))
print(np.mean(num_segments), np.mean(len_segments))
# should be a bit over ~387 and ~144441, we have 75 individuals in the sample
# slay

386.18666666666667 144307.7115072532

In [ ]:
len_segments = []
num_segments = []
ceu_1kg = merged_df[merged_df['pop'] == 'CEU']
for sample_id in ceu_1kg['sample'].unique():
    individual_df = ceu_1kg[ceu_1kg['sample'] == sample_id]
    individual_df['chrom'] = 'chr' + individual_df['chrom']
    individual_bed = pybedtools.BedTool.from_dataframe(individual_df[['chrom', 'pos', 'pos_end']])
    individual_bed = individual_bed.sort().merge().to_dataframe()
    individual_bed['length'] = individual_bed['end'] - individual_bed['start']
    total_length = len(individual_bed)
    num_segments.append(total_length)
    len_segments.append(np.mean(individual_bed['length']))
print(np.mean(num_segments), np.mean(len_segments))
# should be ~428 and ~142868
# werk

404.06060606060606 147328.81985761973

In [ ]:
tools.iasi_2024_raw_to_bed(input_path_metadata=f'{HOMEDIR}/introgression_methods/data/admixfrog_2025/Meta_Data_individuals.csv',
                    input_path=f'{HOMEDIR}/introgression_methods/data/admixfrog_2025/ALL_called_ancestry_segments_updated_3rdDec_2025.csv',
                    output_dir=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/', 
                    population=True, 
                    genomes_source='1KG and SGDP', 
                    individual=True)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/iasi_2024/’: File exists
/wynton/home/capra/ychen39/introgression_methods/introgression_tools/introgression_tools/tools.py:1769: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  metadata_df['sample_name'] = metadata_df['sample_name'].str.replace('.', '-')
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/iasi_2024//bedgraphs’: File exists

Generating merged bedgraph file for Oceania
Generating merged bedgraph file for EUR
Generating merged bedgraph file for EAS
Generating merged bedgraph file for AFR
Generating merged bedgraph file for AMR
Generating merged bedgraph file for CentralAsia
Generating merged bedgraph file for SAS
Output .bed file is located at /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/iasi_2024//iasi_2024_introgressed_frag.bg

In [ ]:
# also save separate dataframe with African individuals only

# get unique IDs with suffix (-1, -2, etc) removed
AFR_with_admixed = list(set([id.split('-')[0] for id in AFR + admixed_AFR]))
AFR = list(set([id.split('-')[0] for id in AFR]))
AFR_with_admixed='|'.join(AFR_with_admixed)
AFR='|'.join(AFR)

admixfrog = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/individual_iasi_2024_introgressed_frag.bg',
                     sep='\t')
admixfrog_afr_admix = admixfrog[admixfrog.ID.str.contains(AFR_with_admixed)][['Chromosome', 'Start', 'End', 'Score']]
# print the AFR ids
print('admixfrog AFR (including admixed) individuals:', len(admixfrog[admixfrog.ID.str.contains(AFR_with_admixed)].ID.unique()))
admixfrog_afr_admix.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/afr_admix.bed', sep='\t', index=False, header=False)

# create merged file
!sort -k1,1 -k2,2n {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/afr_admix.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/afr_admix_sorted.bed
!$BEDTOOLSDIR/bedtools merge -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/afr_admix_sorted.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/afr_with_admix_sorted.bg
# add column of 1s for score
!sed -i 's/$/\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/afr_with_admix_sorted.bg
!rm {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/afr_admix.bed {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/afr_admix_sorted.bed

admixfrog AFR (including admixed) individuals: 42
admixfrog AFR (no admixed) individuals: 10

In [ ]:
admixfrog = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/individual_iasi_2024_introgressed_frag.bg',
                     sep='\t')
len(admixfrog[admixfrog['Ancestry'] == 'AFR']['ID'].unique())

42

### Skov 2023 (X Chromosome)

In [ ]:
# read in file, skipping the first line with the old header
# use the headers that Laurits provided in the email
df = pd.read_csv(f'{HOMEDIR}/introgression_methods/data/skov_2023_X/RestofworldHMMHaploid_samePAR_Archaic.txt', sep='\t', header=None, skiprows=1,
                 names=['name', 'chrom', 'start', 'end', 'length', 'state', 'snps', 'region', 'method', 'dataset', 'MeanProb', 'Altai', 'Denisova', 'Vindija', 'Outgroup', 'sex', 'LongestGap'])
df

,name,chrom,start,end,length,state,snps,region,method,dataset,MeanProb,Altai,Denisova,Vindija,Outgroup,sex,LongestGap
0,S_Mixe-3,X,3117000,3194000,77000,2,8,America,HMM,Sankararaman2016,0.784971,0,0,0,SubAfrica,F,2
1,S_Mixe-3,X,4258000,4278000,20000,2,3,America,HMM,Sankararaman2016,0.603206,0,0,0,SubAfrica,F,1
2,S_Mixe-3,X,4657000,4682000,25000,2,4,America,HMM,Sankararaman2016,0.710400,0,0,0,SubAfrica,F,0
3,S_Mixe-3,X,7110000,7132000,22000,2,3,America,HMM,Sankararaman2016,0.580216,0,0,0,SubAfrica,F,1
4,S_Mixe-3,X,8287000,8297000,10000,2,3,America,HMM,Sankararaman2016,0.514677,0,0,0,SubAfrica,F,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15141,Ust_Ishim,X,149083000,149417000,334000,2,35,WestEurasia,HMM,Sankararaman2016,0.986282,22,5,26,SubAfrica,M,20
15142,Ust_Ishim,X,150415000,150455000,40000,2,4,WestEurasia,HMM,Sankararaman2016,0.613926,0,0,0,SubAfrica,M,6
15143,Ust_Ishim,X,152815000,152837000,22000,2,5,WestEurasia,HMM,Sankararaman2016,0.730166,0,0,0,SubAfrica,M,0
15144,Ust_Ishim,X,153550000,153592000,42000,2,4,WestEurasia,HMM,Sankararaman2016,0.784453,0,0,0,SubAfrica,M,12
15145,Ust_Ishim,X,153704000,153764000,60000,2,4,WestEurasia,HMM,Sankararaman2016,0.547711,0,0,0,SubAfrica,M,2

In [ ]:
SGDP_metadata

,#Sequencing_Panel,Illumina_ID,Sample_ID,Sample_ID(Aliases),SGDP_ID,Population_ID,Region,Country,Town,Contributor,Gender,Latitude,Longitude,DNA_Source,Embargo,"SGDP-lite category: X=FullyPublic, Y=SignedLetterNoDelay, Z=SignedLetterDelay, DO_NOT_USE=do.not.use"
0,B,SS6004478,IHW9118,IHW9118,B_Australian-3,Australian,Oceania,Australia,Cell_line_repository_sampling_location_unknown,ECCAC,U,-13.000000,143.000000,Genomic_from_cell_lines,FullyPublic,X
1,B,SS6004477,IHW9193,IHW9193,B_Australian-4,Australian,Oceania,Australia,Cell_line_repository_sampling_location_unknown,ECCAC,M,-13.000000,143.000000,Genomic_from_cell_lines,FullyPublic,X
2,B,LP6007069-DNA_A01,AV-21,AV-21,B_Crete-1,Crete,WestEurasia,Greece,"Preveliana, Irakleioy",George Stamatoyannopoulos,F,35.166668,25.166666,Genomic_from_blood,FullyPublic,X
3,B,LP6007068-DNA_A01,TZ-11,TZ-11,B_Crete-2,Crete,WestEurasia,Greece,"Psychro ,Lassithi",George Stamatoyannopoulos,M,35.163000,25.445000,Genomic_from_blood,FullyPublic,X
4,B,SS6004467,HGDP01308,HGDP01308,B_Dai-4,Dai,EastAsia,China,?,Howard Cann,M,21.000000,100.000000,Genomic_from_cell_lines,FullyPublic,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,C,LP6005519-DNA_G12,TZSW057,TZSW057,T_Sandawe-2,Sandawe,Africa,Tanzania,"Motto, Kondoa, Dom",Sarah Tishkoff,F,-5.500000,35.500000,Genomic_from_blood,SignedLetterDelay,Z
340,C,LP6005519-DNA_G11,KESN014,KESN014,T_Sengwer-1,Sengwer,Africa,Kenya,Kamoi,Sarah Tishkoff,F,1.100000,35.300000,Genomic_from_blood,SignedLetterDelay,Z
341,C,LP6005519-DNA_H11,KESN030,KESN030,T_Sengwer-2,Sengwer,Africa,Kenya,Kamoi,Sarah Tishkoff,M,1.100000,35.300000,Genomic_from_blood,SignedLetterDelay,Z
342,C,LP6005519-DNA_C10,CATS023,CATS023,T_Tikar_South-1,Tikar_South,Africa,Cameroon,Nditam,Sarah Tishkoff,M,5.400000,11.400000,Genomic_from_blood,SignedLetterDelay,Z
343,C,LP6005519-DNA_D10,CATS005,CATS005,T_Tikar_South-2,Tikar_South,Africa,Cameroon,Ngoume,Sarah Tishkoff,F,5.400000,11.400000,Genomic_from_blood,SignedLetterDelay,Z

In [ ]:
# keep only data from SGDP from SGDP metadata file
SGDP_metadata=pd.read_csv(f'{HOMEDIR}/introgression_methods/data/SGDP_metadata.279public.21signedLetter.44Fan.samples.txt', sep='\t', low_memory=False, encoding='unicode_escape')
sgdp_ids = SGDP_metadata['SGDP_ID'].tolist()
sgdp_df = df[df['name'].isin(sgdp_ids)]
# add superpopulation info from metadata
SGDP_superpop_dict = dict(zip(SGDP_metadata['SGDP_ID'], SGDP_metadata['Region']))
sgdp_df['Ancestry'] = sgdp_df['name'].map(SGDP_superpop_dict)
# rename MeanProb to Score, chrom to Chromosome, start to Start, end to End
sgdp_df.rename(columns={'MeanProb': 'Score', 'chrom': 'Chromosome', 'start': 'Start', 'end': 'End'}, inplace=True)
sgdp_df

,name,Chromosome,Start,End,length,state,snps,region,method,dataset,Score,Altai,Denisova,Vindija,Outgroup,sex,LongestGap,Ancestry
0,S_Mixe-3,X,3117000,3194000,77000,2,8,America,HMM,Sankararaman2016,0.784971,0,0,0,SubAfrica,F,2,America
1,S_Mixe-3,X,4258000,4278000,20000,2,3,America,HMM,Sankararaman2016,0.603206,0,0,0,SubAfrica,F,1,America
2,S_Mixe-3,X,4657000,4682000,25000,2,4,America,HMM,Sankararaman2016,0.710400,0,0,0,SubAfrica,F,0,America
3,S_Mixe-3,X,7110000,7132000,22000,2,3,America,HMM,Sankararaman2016,0.580216,0,0,0,SubAfrica,F,1,America
4,S_Mixe-3,X,8287000,8297000,10000,2,3,America,HMM,Sankararaman2016,0.514677,0,0,0,SubAfrica,F,1,America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14835,S_Lezgin-1,X,145299000,145378000,79000,2,13,WestEurasia,HMM,Sankararaman2016,0.849597,0,7,0,SubAfrica,M,6,WestEurasia
14836,S_Lezgin-1,X,146673000,146689000,16000,2,4,WestEurasia,HMM,Sankararaman2016,0.768092,0,0,0,SubAfrica,M,0,WestEurasia
14837,S_Lezgin-1,X,150403000,150454000,51000,2,6,WestEurasia,HMM,Sankararaman2016,0.898705,0,0,0,SubAfrica,M,6,WestEurasia
14838,S_Lezgin-1,X,152199000,152227000,28000,2,3,WestEurasia,HMM,Sankararaman2016,0.558229,0,0,0,SubAfrica,M,3,WestEurasia
14839,S_Lezgin-1,X,154437000,154485000,48000,2,4,WestEurasia,HMM,Sankararaman2016,0.673866,0,0,0,SubAfrica,M,2,WestEurasia

In [ ]:
# custom function for labelling neanderthal vs denisovan vs both fragments as described
def label_row(row):
    if (row['Denisova'] > row['Vindija']) | (row['Denisova'] > row['Altai']):
        return 'Denisova'
    elif (row['Altai'] > row['Denisova']) | (row['Vindija'] > row['Denisova']):
        return 'Neanderthal'
    else:
        return 'Both'

# apply the custom function
sgdp_df['archaic'] = sgdp_df.apply(label_row, axis=1)
# keep only fragments with mean_prob >/ 0.8
sgdp_df = sgdp_df[sgdp_df['Score'] >= 0.8]
# subset archaic of interest
sgdp_df = sgdp_df[sgdp_df['archaic'] == 'Neanderthal']

sgdp_df

,name,Chromosome,Start,End,length,state,snps,region,method,dataset,Score,Altai,Denisova,Vindija,Outgroup,sex,LongestGap,Ancestry,archaic
15,S_Mixe-3,X,32184000,32329000,145000,2,32,America,HMM,Sankararaman2016,0.955586,17,8,21,SubAfrica,F,2,America,Neanderthal
17,S_Mixe-3,X,33048000,33116000,68000,2,11,America,HMM,Sankararaman2016,0.951556,7,0,8,SubAfrica,F,7,America,Neanderthal
47,S_Mixe-3,X,87691000,87763000,72000,2,6,America,HMM,Sankararaman2016,0.860822,4,1,4,SubAfrica,F,6,America,Neanderthal
61,S_Mixe-3,X,102170000,102589000,419000,2,22,America,HMM,Sankararaman2016,0.861393,11,2,12,SubAfrica,F,8,America,Neanderthal
114,S_Brahui-2,X,86646000,86674000,28000,2,7,SouthAsia,HMM,Sankararaman2016,0.842146,5,1,5,SubAfrica,M,2,SouthAsia,Neanderthal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14709,S_Palestinian-2,X,31910000,31943000,33000,2,7,WestEurasia,HMM,Sankararaman2016,0.905998,5,0,5,SubAfrica,F,1,WestEurasia,Neanderthal
14710,S_Palestinian-2,X,32187000,32329000,142000,2,25,WestEurasia,HMM,Sankararaman2016,0.938892,17,6,18,SubAfrica,F,2,WestEurasia,Neanderthal
14719,S_Palestinian-2,X,95855000,96336000,481000,2,63,WestEurasia,HMM,Sankararaman2016,0.963789,13,1,28,SubAfrica,F,7,WestEurasia,Neanderthal
14816,S_Lezgin-1,X,32076000,32102000,26000,2,6,WestEurasia,HMM,Sankararaman2016,0.900571,1,1,5,SubAfrica,M,1,WestEurasia,Neanderthal
14817,S_Lezgin-1,X,37867000,38267000,400000,2,69,WestEurasia,HMM,Sankararaman2016,0.986589,48,15,47,SubAfrica,M,2,WestEurasia,Neanderthal

In [ ]:
# make directory to store bedgraphs
import re


output_dir = f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/'

os.system(f'mkdir {output_dir}/bedgraphs')
# convert data to bedgraph format
tools.save_bedgraph(sgdp_df, output_dir+'/bedgraphs')
# get ancestries as a list and string separated by a space
ancestries_list = list(sgdp_df['Ancestry'].unique())
# get list of bedgraph files to be merged in the next step, format is full path separated by " \"
merged_bg_files = " \\".join([f'{output_dir}'+'/bedgraphs/'+file for file in os.listdir(f'{output_dir}/bedgraphs') if file.startswith("merged_")])
# get list of ancestries to be used in unionbedg (must be in the same order as the input files)
ancestries_str = re.sub(f'{output_dir}'+'/bedgraphs/'+r'(merged_|\.bg)', '', merged_bg_files)
ancestries_str = re.sub(r'(|\.bg)', '', ancestries_str)
ancestries_str = re.sub(re.escape('\\'), "", ancestries_str)
# create union file at the population level
os.system(f'{BEDTOOLSDIR}/bedtools unionbedg -i {merged_bg_files} -header -names {ancestries_str} > {output_dir}/bedgraphs/union_merged.bg')
# delete intermediate files, keeping only merged files at the ancestral level
os.system(f'cd {output_dir}/bedgraphs; rm -f sorted*.bg')
# read in generated union file
df = pd.read_csv(f'{output_dir}/bedgraphs/union_merged.bg', sep='\t')

# keep only the highest reported score, collapse into one column
df['highest_score'] = df[ancestries_list].max(axis=1)
# drop ancestries
df = df.drop(ancestries_list, axis=1)
# save as a bedgraph
df.to_csv(f'{output_dir}/bedgraphs/union_merged_highest_score.bg', sep='\t', index=False)

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/skov_2023_X//bedgraphs’: File exists

Generating merged bedgraph file for America
Generating merged bedgraph file for SouthAsia
Generating merged bedgraph file for WestEurasia
Generating merged bedgraph file for EastAsia
Generating merged bedgraph file for Oceania
Generating merged bedgraph file for CentralAsiaSiberia
Generating merged bedgraph file for Africa

In [ ]:
# save name -> ID, chrom, start, end, MeanProb
sgdp_df = sgdp_df[['name', 'chrom', 'start', 'end', 'MeanProb']]
sgdp_df.rename(columns={'name': 'ID', 'MeanProb': 'Score', 'chrom': 'Chromosome', 'start': 'Start', 'end': 'End'}, inplace=True)
sgdp_df.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/individual_skov_2023_X_introgressed_frag.bg', sep='\t', index=False, header=True)
# save a version with just bg
sgdp_df_bg = sgdp_df[['Chromosome', 'Start', 'End', 'Score']]
sgdp_df_bg.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/skov_2023_X_introgressed_frag.bg', sep='\t', index=False, header=False)
# save a version with just bed
sgdp_df_bed = sgdp_df[['Chromosome', 'Start', 'End']]
sgdp_df_bed.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/skov_2023_X_introgressed_frag.bed', sep='\t', index=False, header=False)

In [ ]:
sgdp_df

                    ID Chromosome      Start        End     Score
15            S_Mixe-3          X   32184000   32329000  0.955586
17            S_Mixe-3          X   33048000   33116000  0.951556
47            S_Mixe-3          X   87691000   87763000  0.860822
61            S_Mixe-3          X  102170000  102589000  0.861393
114         S_Brahui-2          X   86646000   86674000  0.842146
...                ...        ...        ...        ...       ...
14709  S_Palestinian-2          X   31910000   31943000  0.905998
14710  S_Palestinian-2          X   32187000   32329000  0.938892
14719  S_Palestinian-2          X   95855000   96336000  0.963789
14816       S_Lezgin-1          X   32076000   32102000  0.900571
14817       S_Lezgin-1          X   37867000   38267000  0.986589

[981 rows x 5 columns]

## Create union file. 

This file is generated from the bedgraphs and need to have a # in the first header line, which we did in the previous section

In [ ]:
char_to_find="X"  # Replace X with the character you are looking for

# Read the first line of the file into a variable
first_line=$(head -n 1 "$filename")

# Check if the character is in the first line using pattern matching
if [[ "$first_line" == *"$char_to_find"* ]]; then
  echo "The character '$char_to_find' was found in the first line."
else
  echo "The character '$char_to_find' was not found in the first line."
fi

In [ ]:
## region level - made sorted_union_merged_chr_prefix.bg
methods_dirs = ['chen_2020', 'yuan_2021', 'durvasula_2019', 'steinruecken_2018', 'skov_2020', 'schaefer_2021', 
                'hubisz_2020', 'browning_2018_updated_filtering', 'vernot_2016', 'sankararaman_2014', 'sankararaman_2016_1', 'sankararaman_2016_2',
                'li_2024', 'iasi_2024', 'skov_2018', 'skov_2023_X'] # added after reviews


# Use bedtools complement to get the non-introgressed regions for each method
for method in methods_dirs:
    if 'sankararaman' in method:
        method_name = method.replace('_', '', 1)
    else:
        method_name = method.replace('_', '')
    # specify method dir
    print(method)
    method_dir = f'/introgression_methods/cleaned/introgression_tools/{method}'
    # only keep chrom, start, stop
    !cut -f1,2,3 {HOMEDIR}/{method_dir}/bedgraphs/union_merged.bg > {HOMEDIR}/{method_dir}/bedgraphs/union_merged_prefix.bg
    # Check if the header is in the first line (contains "chrom")), if so, remove it
    !if [[ "$(head -n 1 {HOMEDIR}/{method_dir}/bedgraphs/union_merged_prefix.bg)" == *chrom* ]]; then sed -e '1d' -i {HOMEDIR}/{method_dir}/bedgraphs/union_merged_prefix.bg; fi
    # add chr prefix if chr not in the first line
    !if [[ "$(head -n 1 {HOMEDIR}/{method_dir}/bedgraphs/union_merged_prefix.bg)" == *chr* ]]; then sed -e 's/^/chr/' {HOMEDIR}/{method_dir}/bedgraphs/union_merged_prefix.bg > {HOMEDIR}/{method_dir}/bedgraphs/union_merged_chr_prefix.bg; fi
    # sort both files
    #!sort -k1,1 /wynton/group/capra/data/hg19_fasta/2022-03-14/hg19.fa.fai > {HOMEDIR}/introgression_methods/data/sorted_hg19.fa.fai
    !sort -k1,1 -k2,2n {HOMEDIR}/{method_dir}/bedgraphs/union_merged_chr_prefix.bg > {HOMEDIR}/{method_dir}/bedgraphs/sorted_union_merged_chr_prefix.bg

skov_2023_X

#### With ArchIE

In [ ]:
# bedtools requires '#' to be at the front of each header

# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/vernot_2016_round2/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/bedgraphs/union_merged_header.bg


# Create union file.
!$BEDTOOLSDIR/bedtools unionbedg -i \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/bedgraphs/union_merged_header.bg \
    -header -names argweaverd archaicseeker archie sprime vernot_2016 sankararaman_2014 sankararaman_2016_1 sankararaman_2016_2 hmmix20 steinruecken_2018 sarge hmmix18 admixfrog ibdmix24 hmmix23_X > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed

In [ ]:
# make overlap file with only bed and chr prefix: overlap_bed_only_no_header_chr_prefix.bg

# only keep chrom, start, stop
!cut -f1,2,3 {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_bed_only.bed
# remove header
!sed -e '1d' -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_bed_only.bed
# add chr prefix
!sed -e 's/^/chr/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_bed_only.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/overlap_bed_only_no_header_chr_prefix.bg

# create merged file. This file is generated from the bedgraphs and need to have a # in the first header line, which we did in the previous section
!$BEDTOOLSDIR/bedtools merge -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/overlap_bed_only_no_header_chr_prefix.bg \
    > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/merged_all_methods.bed

In [ ]:
overlap = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed', sep='\t', low_memory=False)
# replace 0s with NA
overlap.replace(0, np.nan, inplace=True)
# add length data
overlap['length'] = overlap['end'] - overlap['start']
overlap

overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed', sep='\t', index=False)

# save bed file version of all identified introgressed segments across methods
overlap[['chrom', 'start', 'end']].to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/overlap_bed_only.bed', sep='\t', index=False)

# first, convert dataframe to boolean values
# exclude for boolean
exclude_columns = ['chrom', 'start', 'end', 'length']
# convert to boolean
boolean_overlap = overlap.copy()
boolean_overlap[boolean_overlap.columns.difference(exclude_columns)] = boolean_overlap[boolean_overlap.columns.difference(exclude_columns)].applymap(lambda x: pd.notna(x))
boolean_overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap.bed', sep='\t', index=False)
boolean_overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_no_header.bed', sep='\t', index=False, header=False)

# drop chrom, start, end
boolean_overlap = boolean_overlap.drop(['chrom', 'start', 'end'], axis=1)
boolean_overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_no_bed.bed', sep='\t', index=False)
boolean_overlap

,argweaverd,archaicseeker,archie,sprime,vernot_2016,sankararaman_2014,sankararaman_2016_1,sankararaman_2016_2,hmmix20,steinruecken_2018,sarge,hmmix18,admixfrog,ibdmix24,hmmix23_X,length
0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,4580
1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,5610
2,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,4454
3,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,22746
4,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,9495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445196,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,16450
445197,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,75368
445198,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,37507
445199,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,3066
445200,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1500

#### Union - No ARGWeaver-D

In [ ]:
## REGION LEVEL FILE
# Create union file without ARGWeaver-D (hubisz 2020)
# Create union file.
!$BEDTOOLSDIR/bedtools unionbedg -i \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/bedgraphs/union_merged_header.bg \
    -header -names archaicseeker archie sprime vernot_2016 sankararaman_2014 sankararaman_2016_1 sankararaman_2016_2 hmmix20 steinruecken_2018 sarge hmmix18 admixfrog ibdmix24 hmmix23_X > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_argweaver.bg


# only keep chrom, start, stop
!cut -f1,2,3 {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_argweaver.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_argweaver.bed
# remove header: Check if the header is in the first line (contains "chrom")), if so, remove it
!if [[ "$(head -n 1 {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_argweaver.bed)" == *chrom* ]]; then sed -e '1d' -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_argweaver.bed; fi
# add chr prefix
!if [[ "$(head -n 1 {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_argweaver.bed)" == *chr* ]]; then sed -e 's/^/chr/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_argweaver.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_argweaver_chr_prefix.bed; fi

# Create merged file. This file is generated from the bedgraphs and need to have a # in the first header line, which we did in the previous section
# !$BEDTOOLSDIR/bedtools merge -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/overlap_bed_only_no_argweaver_no_header_chr_prefix.bg \
#     > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/merged_all_methods_no_argweaver.bed

# ## Region level
# !{BEDTOOLSDIR}/bedtools intersect -a {HOMEDIR}/introgression_methods/cleaned/introgression_tools/overlap_bed_only_no_argweaver_no_header_chr_prefix.bg \
#     -b {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/sorted_union_merged_chr_prefix.bg \
#     -C -names ibdmix20 archaicseeker archie sprime vernot_2016 sankararaman_2014 sankararaman_2016_1 sankararaman_2016_2 skov_2020 steinruecken_2018 sarge skov_2018 admixfrog ibdmix24 \
#    > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/region_intersect_for_boolean_no_argweaver.bed

In [ ]:
## BASE PAIRS LEVEL
overlap = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_argweaver.bg', sep='\t', low_memory=False)
# replace 0s with NA
overlap.replace(0, np.nan, inplace=True)
# add length data
overlap['length'] = overlap['end'] - overlap['start']
overlap

overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_argweaver.bed', sep='\t', index=False)

# save bed file version of all identified introgressed segments across methods
overlap[['chrom', 'start', 'end']].to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/overlap_no_argweaver_bed_only.bed', sep='\t', index=False)

# first, convert dataframe to boolean values
# List of columns to exclude
exclude_columns = ['chrom', 'start', 'end', 'length']
# Convert non-NA values to True and NA values to False, excluding specified columns
boolean_overlap = overlap.copy()
boolean_overlap[boolean_overlap.columns.difference(exclude_columns)] = boolean_overlap[boolean_overlap.columns.difference(exclude_columns)].applymap(lambda x: pd.notna(x))
boolean_overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_no_argweaver.bed', sep='\t', index=False)
boolean_overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_no_argweaver_no_header.bed', sep='\t', index=False, header=False)

# drop chrom, start, end
boolean_overlap = boolean_overlap.drop(['chrom', 'start', 'end'], axis=1)
boolean_overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_no_argweaver_no_bed.bed', sep='\t', index=False)
boolean_overlap

## REGION LEVEL

# # convert dataframe to boolean values
# # read in regions overlap file that takes into account different loci by different algorithms
# region_overlap = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/region_intersect_for_boolean_no_argweaver.bed', sep='\t', low_memory=False, names=['chr', 'start', 'end', 'method', 'regions'])
# # Group by chrom, start, end and 
# grouped = region_overlap.groupby(['chr', 'start', 'end', 'method']).sum().reset_index()
# # Pivot table to turn methods -> columns
# pivot_table = grouped.pivot_table(index=['chr', 'start', 'end'], columns='method', values='regions', fill_value=0)
# # Reset index to convert to a flat DataFrame
# pivot_table.reset_index(inplace=True)

# # List of columns to exclude
# exclude_columns = ['chr', 'start', 'end']
# # Convert non-NA values to True and NA values to False, excluding specified columns
# boolean_region_overlap = pivot_table.copy()
# # replace 0s with NA
# boolean_region_overlap.replace(0, np.nan, inplace=True)
# # replace with boolean values
# boolean_region_overlap[boolean_region_overlap.columns.difference(exclude_columns)] = boolean_region_overlap[boolean_region_overlap.columns.difference(exclude_columns)].applymap(lambda x: pd.notna(x))

# boolean_region_overlap.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_region_overlap_no_argweaver.bed', sep='\t', index=False)
# # drop chrom, start, end
# boolean_region_overlap_no_bed = boolean_region_overlap.drop(['chr', 'start', 'end'], axis=1)
# boolean_region_overlap_no_bed.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_region_overlap_no_argweaver_no_bed', sep='\t', index=False)
# boolean_region_overlap

,archaicseeker,archie,sprime,vernot_2016,sankararaman_2014,sankararaman_2016_1,sankararaman_2016_2,hmmix20,steinruecken_2018,sarge,hmmix18,admixfrog,ibdmix24,hmmix23_X,length
0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,4580
1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,5610
2,True,False,False,False,False,False,False,False,False,False,False,False,False,False,4454
3,True,False,False,False,False,False,False,False,False,False,False,False,False,False,22746
4,True,False,False,False,False,False,False,False,False,False,False,False,False,False,9495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439467,False,False,False,False,False,True,False,False,False,False,False,False,False,False,16450
439468,False,False,False,False,False,True,False,False,False,False,False,False,False,False,75368
439469,False,False,False,False,False,True,False,False,False,False,False,False,False,False,37507
439470,False,False,False,False,False,True,False,False,False,False,False,False,False,False,3066
439471,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1500

#### Back to including ARGweaver-D

In [ ]:
all_methods_concat_pops

,chrom,start,end,WestEurasia,Africa,Oceania,EAS,SAS,EUR,CEU,...,CHBS,Africa2,EastAsia,CentralAsiaSiberia,America,SouthAsia,MiddleEast,CentralSouthAsia,AdmixedAFR,AFR
0,1,2898680,2920300,500.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
1,1,3413191,3457679,500.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
2,1,3604140,3625300,0.0,0.0,1000.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
3,1,4027670,4057990,0.0,0.0,500.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
4,1,15340170,15372570,0.0,0.0,500.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,X,145110000,145143000,0.0,0.0,0.916934,0.0,0.0,0.0,0.0,...,0.0,0.0,0.831692,0.901733,0.0,0.000000,0.0,0.0,0.0,0.0
404,X,145143000,145153000,0.0,0.0,0.916934,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
405,X,145395000,145546000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.900577,0.0,0.0,0.0,0.0
406,X,150889000,150931000,0.0,0.0,0.922652,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
407,X,151194000,151253000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.855169,0.0,0.0,0.0,0.0

In [ ]:
hubisz_2020_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs/union_merged.bg', sep='\t')
yuan_2021_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged.bg', sep='\t')
durvasula_2019_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/union_merged.bg', sep='\t', names=['chrom', 'start', 'end', 'CEU'])
browning_2018_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/bedgraphs/union_merged.bg', sep='\t')
vernot_2016_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/union_merged.bg', sep='\t')
sankararaman_2014_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged.bg', sep='\t')
sankararaman_2016_1_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged.bg', sep='\t')
sankararaman_2016_2_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged.bg', sep='\t')
steinruecken_2018_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged.bg', sep='\t')
schaefer_2021_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged.bg', sep='\t')
skov_2020_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_highest_score.bg', sep='\t',
                                names=['chrom', 'start', 'end', 'highest_score'])
skov_2020_pops.rename(columns={'highest_score': 'Icelandic'}, inplace=True)
skov_2018_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/union_merged.bg', sep='\t')
li_2024_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/union_merged.bg', sep='\t')
iasi_2024_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/union_merged.bg', sep='\t')
skov_2023_X_pops = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/bedgraphs/union_merged.bg', sep='\t')


# Combine each separate file into one massive file
all_methods_concat_pops = pd.concat([hubisz_2020_pops, yuan_2021_pops, durvasula_2019_pops, browning_2018_pops, 
                                     vernot_2016_pops, sankararaman_2014_pops, sankararaman_2016_1_pops, sankararaman_2016_2_pops,
                                    skov_2020_pops, steinruecken_2018_pops, schaefer_2021_pops, skov_2018_pops, li_2024_pops, iasi_2024_pops, skov_2023_X_pops], axis=0)

# remove chr prefix for consistency, need astype(str) first to avoid error resulting in NAs due to integer not being a string
all_methods_concat_pops['chrom'].astype(str).str.replace('^chr', '', regex=True)

all_methods_concat_pops = all_methods_concat_pops.fillna(0)
all_methods_concat_pops.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops.bed', sep='\t', index=False)

# add '#' for header
#!sed -i '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops.bed 
# collapse extra tabs
#!tr -s '\t' '\t' < {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops_header_tabs_collapse.bed
 # remove extra tabs and sort file
#!sed 's/\t$//' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops_header_tabs_collapse.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops_tab_removed.bed
# remove header
#!sed -e '1d' -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops_tab_removed.bed
#!sort -k 1,1 -k2,2n {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops_tab_removed.bed > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops.bed
# re-add header after sorting
# Extract the first line from the source file
#!read -r first_line<$HOMEDIR/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops_tab_removed.bed
# add header line
#!cp {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops.bed {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops_header.bed
#!sed -i '1s/^/#chrom\tstart\tend\tEAS\tEUR\tAMR\tSAS\tAFR\tAfrica\tOceania\tWestEurasia\tCEU\tASN\tPNG\tCentralAsia\tIcelandic\tCHBS\tEastAsia\tAfrica2\tAmerica\tCentralAsiaSiberia\tSouthAsia\n/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops_header.bed
# had to hard code because sed was giving me such a hard time inserting first line from another file

# remove intermediate files
#!rm {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops_header_tabs_collapse.bed \
#{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_concat_pops_tab_removed.bed

In [ ]:
all_methods_concat_pops.columns

Index(['chrom', 'start', 'end', 'WestEurasia', 'Africa', 'Oceania', 'EAS',
       'SAS', 'EUR', 'CEU', 'AMR', 'PNG', 'CentralAsia', 'Icelandic', 'CHBS',
       'Africa2', 'EastAsia', 'CentralAsiaSiberia', 'America', 'SouthAsia',
       'MiddleEast', 'CentralSouthAsia', 'AdmixedAFR', 'AFR'],
      dtype='object')

In [ ]:
## region level - made sorted_union_merged_chr_prefix.bg
methods_dirs = ['yuan_2021', 'durvasula_2019', 'steinruecken_2018', 'skov_2020', 'schaefer_2021', 
                'hubisz_2020', 'browning_2018_updated_filtering', 'vernot_2016', 'sankararaman_2014', 'sankararaman_2016_1', 'sankararaman_2016_2',
                'li_2024', 'iasi_2024', 'skov_2018', 'skov_2023_X'] # added after reviews# Use bedtools complement to get the non-introgressed regions for each method
for method in methods_dirs:
    if 'sankararaman' in method:
        method_name = method.replace('_', '', 1)
    else:
        method_name = method.replace('_', '')
    # specify method dir
    print(method)
    method_dir = f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/{method}'
    # only keep chrom, start, stop
    !cut -f1,2,3 {method_dir}/bedgraphs/union_merged.bg > {method_dir}/bedgraphs/union_merged_prefix.bg
    # Check if the header is in the first line (contains "chrom")), if so, remove it
    !if [[ "$(head -n 1 {method_dir}/bedgraphs/union_merged_prefix.bg)" == *chrom* ]]; then sed -e '1d' -i {method_dir}/bedgraphs/union_merged_prefix.bg; fi
    # add chr prefix if chr not in the first line
    !if [[ "$(head -n 1 {method_dir}/bedgraphs/union_merged_prefix.bg)" == *chr* ]]; then sed -e 's/^/chr/' {method_dir}/bedgraphs/union_merged_prefix.bg > {method_dir}/bedgraphs/union_merged_chr_prefix.bg; fi
    # sort both files
    !sort -k1,1 /wynton/group/capra/data/hg19_fasta/2022-03-14/hg19.fa.fai > {HOMEDIR}/introgression_methods/data/sorted_hg19.fa.fai
    !sort -k1,1 -k2,2n {method_dir}/bedgraphs/union_merged_chr_prefix.bg > {method_dir}/bedgraphs/sorted_union_merged_chr_prefix.bg
    # run bedtools complement
    # os.system(f'{BEDTOOLSDIR}/bedtools complement -L -i {method_dir}/bedgraphs/sorted_union_merged_chr_prefix.bg -g {HOMEDIR}/introgression_methods/data/sorted_hg19.fa.fai > {method_dir}/bedgraphs/complement.bg')
    # # subtract gaps
    # os.system(f'{BEDTOOLSDIR}/bedtools subtract -a {HOMEDIR}/{method_dir}/bedgraphs/complement.bg -b {HOMEDIR}/introgression_methods/data/hg19_gaps.txt > {HOMEDIR}/{method_dir}/complement_gaps_removed.bg')
    # # keep desert regions only in filtered regions from the Nean genome - min filtering
    # os.system(f'{BEDTOOLSDIR}/bedtools intersect -a {HOMEDIR}/{method_dir}/complement_gaps_removed.bg -b {HOMEDIR}/introgression_methods/data/altai_minimal_filters/AltaiNea.map35_50.MQ30.Cov.indels.TRF_chr_prefix.bed > {HOMEDIR}/{method_dir}/complement_gaps_removed_altai_filtered_min.bg')
    # # keep desert regions only in filtered regions from the Nean genome - more extensive filtering from Altai
    # os.system(f'{BEDTOOLSDIR}/bedtools intersect -a {HOMEDIR}/{method_dir}/complement_gaps_removed.bg -b {HOMEDIR}/introgression_methods/data/vindija_filtered_regions/altai_filtered_chr_prefix.bed > {HOMEDIR}/{method_dir}/complement_gaps_removed_altai_filtered.bg')

skov_2023_X

In [ ]:
# make a version with different universe: each unique combination of detected regions is a separate region
## THIS ONE IS THE FINALIZED ONE
!{BEDTOOLSDIR}/bedtools intersect -a {HOMEDIR}/introgression_methods/cleaned/introgression_tools/overlap_bed_only_no_header_chr_prefix.bg \
    -b {HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/sorted_union_merged_chr_prefix.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/sorted_union_merged_chr_prefix.bg \
    -C -names argweaverd archaicseeker archie sprime vernot_2016 sankararaman_2014 sankararaman_2016_1 sankararaman_2016_2 skov_2020 steinruecken_2018 sarge skov_2018 admixfrog ibdmix24 \
   > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/region_intersect_for_boolean.bed

Error: Unable to open file /wynton/home/capra/ychen39//introgression_methods/cleaned/introgression_tools/browning_2018/bedgraphs/sorted_union_merged_chr_prefix.bg. Exiting.

### Without ArchIE, with ARGweaver-D -- revisions

In [ ]:
# bedtools requires '#' to be at the front of each header

# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/vernot_2016_round2/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged_header.bg
# !sed '1,1s/^/#/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged_highest_score.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged_header.bg

# Create union file.
!$BEDTOOLSDIR/bedtools unionbedg -i \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/union_merged_header.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/bedgraphs/union_merged_header.bg \
    -header -names argweaverd archaicseeker sprime vernot_2016 sankararaman_2014 sankararaman_2016_1 sankararaman_2016_2 skov_2020 steinruecken_2018 sarge skov_2018 admixfrog ibdmix24 skov_2023_X > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods_no_archie.bed

In [ ]:
method_file_dict = {
    'ARGweaverD' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs/union_merged_highest_score.bg',
    'ArchaicSeeker2' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged_highest_score.bg',
    'Admixfrog' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/union_merged_highest_score.bg',
    'Sprime' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/bedgraphs/union_merged_highest_score.bg',
    'Sstar' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/union_merged_highest_score.bg',
    'Sankararaman14' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged_highest_score.bg',
    'Sankararaman161' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged_highest_score.bg',
    'Sankararaman162' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged_highest_score.bg',
    'hmmix20' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_highest_score.bg',
    'DICALADMIX' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged_highest_score.bg',
    'SARGE' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged_highest_score.bg',
    'IBDMix24' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/union_merged_highest_score.bg',
    'hmmix18' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/union_merged_highest_score.bg',
    'hmmix23_X' : f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2023_X/bedgraphs/union_merged_highest_score.bg'
}

for method, file_path in method_file_dict.items():

    # read bg file as bed file
    bed_df = pd.read_csv(f'{file_path}', 
                            sep='\t', 
                            names=['chrom', 'start', 'end'], 
                            usecols=[0, 1, 2])

    # save bedtool as the variable name (for unionbedg later)
    globals()[method] = pybedtools.BedTool.from_dataframe(bed_df).sort().merge()
    # also save it temporarily to print stats
    BedTool = pybedtools.BedTool.from_dataframe(bed_df).sort().merge()
    # print stats
    print(method, "has", len(BedTool.to_dataframe()), "distinct number of regions and total length of", BedTool.total_coverage())

    BedTool.to_dataframe().to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/union/{method}_full_map.bed', sep='\t', index=False, header=False)

ARGweaverD has 2742 distinct number of regions and total length of 136667575
ArchaicSeeker2 has 12776 distinct number of regions and total length of 1534838051
Admixfrog has 3097 distinct number of regions and total length of 1415066287
Sprime has 1121 distinct number of regions and total length of 590956654
Sstar has 7300 distinct number of regions and total length of 1339505007
Sankararaman14 has 4530 distinct number of regions and total length of 1117531142
Sankararaman161 has 3792 distinct number of regions and total length of 1558018928
Sankararaman162 has 2606 distinct number of regions and total length of 1141804104
hmmix20 has 3202 distinct number of regions and total length of 889069710
DICALADMIX has 13235 distinct number of regions and total length of 1023339000
SARGE has 42719 distinct number of regions and total length of 1068860156
IBDMix24 has 4768 distinct number of regions and total length of 1673742326
hmmix18 has 4029 distinct number of regions and total length of 1582068793
hmmix23_X has 87 distinct number of regions and total length of 27078000

In [ ]:
%%bash

# create union file of all methods

cd /wynton/home/capra/ychen39/introgression_methods/cleaned/introgression_tools/union/

cat Admixfrog_full_map.bed IBDMix24_full_map.bed ArchaicSeeker2_full_map.bed Sankararaman14_full_map.bed \
    ARGweaverD_full_map.bed Sankararaman161_full_map.bed DICALADMIX_full_map.bed Sankararaman162_full_map.bed \
    hmmix18_full_map.bed SARGE_full_map.bed hmmix20_full_map.bed Sprime_full_map.bed \
    Sstar_full_map.bed | sort -k1,1 -k2,2n | bedtools merge > /wynton/home/capra/ychen39/introgression_methods/cleaned/introgression_tools/union/union_no_archie.bed

### No ARGWeaver-D, subsetted to a shared length across them, keeping the highest score

In [ ]:
# remove header from 
methods_dirs = ['yuan_2021', 'durvasula_2019', 'steinruecken_2018', 'skov_2020', 'schaefer_2021', 
                'hubisz_2020', 'browning_2018_updated_filtering', 'vernot_2016', 'sankararaman_2014', 'sankararaman_2016_1', 'sankararaman_2016_2',
                'li_2024', 'iasi_2024', 'skov_2018'] # added after reviews 
# Use bedtools complement to get the non-introgressed regions for each method
for method in methods_dirs:
    method_dir = f'/introgression_methods/cleaned/introgression_tools/{method}'
    with open(f'{HOMEDIR}/{method_dir}/bedgraphs/union_merged_highest_score.bg', 'r') as f:
        first_line = f.readline()
        if 'chrom' in first_line.lower():
            !sed -e '1d' -i {HOMEDIR}/{method_dir}/bedgraphs/union_merged_highest_score.bg

In [ ]:
# empty dict to hold proportions
proportions = {}
for method in methods_dirs:
    if method=='hubisz_2020':
        continue
    else:
        print(method)
        method_dir = f'/introgression_methods/cleaned/introgression_tools/{method}'
        df = pd.read_csv(f'{HOMEDIR}/{method_dir}/bedgraphs/union_merged_highest_score.bg', sep='\t', low_memory=False,
                        names=['chrom', 'start', 'end', 'score'])
        # compute length
        df['length'] = df['end'] - df['start']
        # compute the minumum amount of introgression across people
        min_sum = df['length'].sum().min()
        # add the minimum amount to the dict
        proportions[method] = min_sum
# get the smallest value to use as length_threshold
length_threshold = min(proportions.values())
print(proportions)
print(length_threshold)

yuan_2021
durvasula_2019
steinruecken_2018
skov_2020
schaefer_2021
browning_2018_updated_filtering
vernot_2016
sankararaman_2014
sankararaman_2016_1
sankararaman_2016_2
li_2024
iasi_2024
skov_2018
{'yuan_2021': 1534838051, 'durvasula_2019': 793900000, 'steinruecken_2018': 1023339000, 'skov_2020': 889069710, 'schaefer_2021': 1068860156, 'browning_2018_updated_filtering': 590956654, 'vernot_2016': 1339505007, 'sankararaman_2014': 1117531142, 'sankararaman_2016_1': 1558018928, 'sankararaman_2016_2': 1141804104, 'li_2024': 1673742326, 'iasi_2024': 1415066287, 'skov_2018': 1582068793}
590956654

In [ ]:
# generate subsetted overlap file

boolean_overlap_shared_length_highest_scores = tools.generate_overlap(input_files_string=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/union_merged_highest_score.bg',
    input_files_names_str='archaicseeker archie sprime vernot_2016 sankararaman_2014 sankararaman_2016_1 \
                           sankararaman_2016_2 hmmix20 steinruecken_2018 sarge hmmix18 ibdmix24 admixfrog',
    output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_shared_length_highest_scores_updated.bg',
    boolean=True, autosomes=True, length_threshold=590956654, bed_only=True)

In [ ]:
# also a version with EUR regions only
boolean_overlap_shared_length_highest_scores_EUR = tools.generate_overlap(input_files_string=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/bedgraphs/union_merged_highest_score.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/merged_EUR.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/merged_EUR.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018/bedgraphs/merged_EUR.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/merged_EUR.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/merged_EUR.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/merged_EUR.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/merged_EUR.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/merged_Icelandic.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/merged_CEU.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/merged_WestEurasia.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/merged_EUR.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/merged_EUR.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/merged_EUR.bg',
                                           input_files_names_str='ibdmix archaicseeker archie sprime vernot_2016 sankararaman_2014 sankararaman_2016_1 sankararaman_2016_2 skov_2020 steinruecken_2018 sarge skov_2018 admixfrog ibdmix24',
                                           output_file_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap_shared_length_highest_scores_EUR.bed',
                                           boolean=True, autosomes=True, length_threshold=length_threshold)

SyntaxError: unterminated string literal (detected at line 16) (987789709.py, line 16)

In [ ]:
# make archie_individual_vs_other_methods by concatenating all individual-level data
# read in all the data
# make a dictionary to get from Illumina_ID to SGDP_ID

ibdmix_individual=pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/individual_nean_chen2020_frag.bed', sep='\t', low_memory=False)
archaicseeker2_individual=pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/individual_nean_yuan2021_frag.bed', sep='\t', low_memory=False)
archaicseeker2_individual['ID'] = archaicseeker2_individual['ID'].str.split('_').str[0]
archie_individual=pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/individual_nean_durvasula2019_frag.bed', sep='\t', low_memory=False)
dicaladmix_individual=pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/individual_introgressed_steinruecken2018_frag.bed', sep='\t', low_memory=False)
dicaladmix_individual['Chromosome'] = dicaladmix_individual['Chromosome'].str.replace('chr', '')
sankararaman_2014_individual=pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/1kgids_individual_neanderthal_introgressed_fragments_pops.bed', sep='\t', low_memory=False)
vernot_2016_individual=pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/neanderthal_introgressed_haplotypes_individual.bed', sep='\t', low_memory=False)
admixfrog_individual=pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/individual_iasi_2024_introgressed_frag.bg', sep='\t', low_memory=False)
ibdmix_2024_individual=pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/individual_ibdmix_2024_introgressed_frag.bg', sep='\t', low_memory=False)
hmmix18_individual=pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/individual_nean_skov2018_frag.bed', sep='\t', low_memory=False)

dfs_dict = {'ArchaicSeeker2':archaicseeker2_individual, 
       'ArchIE':archie_individual,
        'DICALADMIX':dicaladmix_individual,
           'Sankararaman14':sankararaman_2014_individual,
           'SStar':vernot_2016_individual,
           'admixfrog':admixfrog_individual,
           'IBDMix':ibdmix_2024_individual,
           'hmmix18':hmmix18_individual}

In [ ]:
individual_concat = pd.concat([df.assign(Algorithm=k) for k,df in dfs_dict.items()])
# save to file
individual_concat.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/archie_individual_vs_other_methods.bg', sep='\t', index=False)

In [ ]:
individual_concat['Algorithm'].unique()

array(['ArchaicSeeker2', 'ArchIE', 'DICALADMIX', 'Sankararaman14',
       'SStar', 'admixfrog', 'IBDMix', 'hmmix18'], dtype=object)

## Generate previously computed deserts

Available deserts:
- Chen 2020 (in Table S8)
- Skov 2020 (Supplementary Dataset 4, 41586_2020_2225_MOESM6_ESM, "This dataset reports the chrom, desert number, start, mean windows called as archaic, number of called and total number of genes.")
- Vernot 2016 (In Chen 2020 Table S8)
- Sankararaman 2016 (previously emailed Dr. Sankararaman)
- Yuan 2021 (Supplementary Data 6)
- Iasi 2024 (need to compute ourselves? wait it looks like they don't actually provide deserts)

#### Merge deserts

In [ ]:
## manually write .bed files for Chen 2020 and Vernot deserts:
chen_2020_deserts = {
    'chrom': [1, 3, 7, 8],
    'start': [105400000, 74100000, 106200000, 49400000],
    'end': [120600000, 89300000, 123200000, 66500000]
}

chen_2020_deserts_df = pd.DataFrame(chen_2020_deserts)
chen_2020_deserts_df.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/original_deserts.bg', header=False, sep='\t', index=False)

# save version with chr prefix
chen_2020_deserts_df['chrom'] = 'chr' + chen_2020_deserts_df['chrom'].astype(str)
chen_2020_deserts_df.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/original_deserts_chr_prefix.bg', header=False, sep='\t', index=False)

vernot_2016_deserts = {
    'chrom': [1, 2, 3, 7, 8, 18],
    'start': [102200000, 201100000, 76500000, 106300000, 53900000, 25000000],
    'end': [114900000, 211500000, 90500000, 124700000, 66000000, 41800000]
}

vernot_2016_deserts_df = pd.DataFrame(vernot_2016_deserts)
vernot_2016_deserts_df.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/original_deserts.bg', header=False, sep='\t', index=False)

# save version with chr prefix
vernot_2016_deserts_df['chrom'] = 'chr' + vernot_2016_deserts_df['chrom'].astype(str)
vernot_2016_deserts_df.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/original_deserts_chr_prefix.bg', header=False, sep='\t', index=False)

# load in ArchaicSeeker2 deserts file (supplementary figure 6)
yuan_2021_deserts=pd.read_excel(f'{HOMEDIR}/introgression_methods/data/archaicseeker2.0_yuan_et_al_2021/41467_2021_26503_MOESM9_ESM.xlsx')
# save only as bed file with chrom, start, end
yuan_2021_deserts[['Chromosome', 'Start (bp)', 'End (bp)']].to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/original_deserts.bg', header=False, sep='\t', index=False)

In [ ]:
# Sankararaman deserts are already in a cleaned .bed format, copy over to cleaned directory
! cp {HOMEDIR}/introgression_methods/data/sankararaman_2016/deserts/sankararaman16_nean-deserts_hg19.bed {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/original_deserts_chr_prefix.bg

sankararaman_2016_deserts = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/original_deserts_chr_prefix.bg', sep='\t', names=['chrom', 'start', 'end'])
sankararaman_2016_deserts['chrom'] = sankararaman_2016_deserts['chrom'].str.replace('chr', '')
sankararaman_2016_deserts.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/original_deserts.bg', header=False, sep='\t', index=False)

In [ ]:
## Load in Skov 2020 deserts file -- Need to liftover from hg38 to hg19
skov_2020_deserts = pd.read_csv(f'{HOMEDIR}/introgression_methods/data/skov_2020/41586_2020_2225_MOESM6_ESM.txt', sep='\t')
skov_2020_deserts = skov_2020_deserts[['chrom', 'start', 'end']]
skov_2020_deserts['start'] = np.int64(skov_2020_deserts['start'])
skov_2020_deserts['end'] = np.int64(skov_2020_deserts['end'])
# add chr prefix
skov_2020_deserts['chrom'] = 'chr' + skov_2020_deserts['chrom']
#skov_2020_deserts.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/original_deserts_hg38.bg', header=False, sep='\t', index=False)

In [ ]:
skov_2020_deserts = pd.read_csv(f'{HOMEDIR}/introgression_methods/data/skov_2020/41586_2020_2225_MOESM6_ESM.txt', sep='\t')

np.sum(skov_2020_deserts.mean_called)

0

In [ ]:
# run liftover
!/wynton/group/capra/bin/liftOver/liftOver \
{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/original_deserts_hg38.bg \
{HOMEDIR}/introgression_methods/data/skov_2020/hg38_to_hg19_liftover/hg38ToHg19.over.chain.gz \
{HOMEDIR}/introgression_methods/data/skov_2020/hg38_to_hg19_liftover/original_deserts_hg19.bed \
{HOMEDIR}/introgression_methods/data/skov_2020/hg38_to_hg19_liftover/deserts_unlifted.bed

# copy final lifted file to cleaned directory
!cp {HOMEDIR}/introgression_methods/data/skov_2020/hg38_to_hg19_liftover/original_deserts_hg19.bed {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/original_deserts_chr_prefix.bg
# remove 'chr' prefix in cleaned file
skov_2020_deserts = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/original_deserts_chr_prefix.bg', sep='\t', names=['chrom', 'start', 'end'])
skov_2020_deserts['chrom'] = skov_2020_deserts['chrom'].str.replace('chr', '')
skov_2020_deserts.to_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/original_deserts.bg', header=False, sep='\t', index=False)

Reading liftover chains
Mapping coordinates

After LiftOver, we went from 281 desert regions in hg38 -> 268 desert regions in hg19.

### Combined desert file

In [ ]:
# sort the bg file
bedops_dir='/wynton/home/cbi/shared/software/CBI/bedops-2.4.41/bin/'
!{bedops_dir}/sort-bed --unique {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/original_deserts.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/sorted_original_deserts.bg
!{bedops_dir}/sort-bed --unique {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/original_deserts.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/sorted_original_deserts.bg
!{bedops_dir}/sort-bed --unique {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/original_deserts.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/sorted_original_deserts.bg
!{bedops_dir}/sort-bed --unique {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/original_deserts.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/sorted_original_deserts.bg
!{bedops_dir}/sort-bed --unique {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/original_deserts.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/sorted_original_deserts.bg
# !{bedops_dir}/sort-bed --unique {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/original_deserts.bg > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/sorted_original_deserts.bg

# add 1s
!sed -i 's/$/&\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/sorted_original_deserts.bg
!sed -i 's/$/&\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/sorted_original_deserts.bg
!sed -i 's/$/&\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/sorted_original_deserts.bg
!sed -i 's/$/&\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/sorted_original_deserts.bg
!sed -i 's/$/&\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/sorted_original_deserts.bg
# !sed -i 's/$/&\t1/' {HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/sorted_original_deserts.bg


# generate a combined file
!$BEDTOOLSDIR/bedtools unionbedg -i {HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/sorted_original_deserts.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/sorted_original_deserts.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/chen_2020/sorted_original_deserts.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/sorted_original_deserts.bg \
    {HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/sorted_original_deserts.bg \
    -header -names sankararaman_2016_1 skov_2020 chen_2020 vernot_2016 yuan_2021 > {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_deserts.bed

# Liftover all introgression maps to hg38 and T2T

In [ ]:
!cp /wynton/home/capra/ychen39/introgression_methods/cleaned/introgression_tools/african_boolean_overlap_no_admix.bg /wynton/home/capra/ychen39/introgression_methods/cleaned/github_data/github/data/hg19/introgression_maps/african_boolean_overlap_no_admix.bg

!cp /wynton/home/capra/ychen39/introgression_methods/cleaned/introgression_tools/all_methods.bed /wynton/home/capra/ychen39/introgression_methods/cleaned/github_data/github/data/hg19/introgression_maps/african_boolean_overlap_no_admix.bg

In [54]:
# make dir along with all subdirs
github_dir = '/wynton/home/capra/ychen39/introgression_methods/cleaned/github_data_round_2/github/data/hg19/'
os.makedirs(github_dir, exist_ok=True)

# for each method_dir, make that directory
for method in methods_dirs:
    method_dir = f'{github_dir}/introgression_maps/maps_by_method/{method}'
    if not os.path.exists(method_dir):
        os.makedirs(method_dir)

# copy some misc files - all deserts, all_methods, african_boolean_overlap, african_boolean_overlap_no_admix, individual-level data (ceu and afr)
!cp {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_deserts.bed {github_dir}/all_deserts.bg
# insert chr prefix
all_deserts = pd.read_csv(f'{github_dir}/all_deserts.bg', sep='\t', low_memory=False)
all_deserts['chrom'] = 'chr' + all_deserts['chrom'].astype(str)
all_deserts.to_csv(f'{github_dir}/all_deserts.bg', sep='\t', index=False, header=True)

!cp {HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed {github_dir}/introgression_maps/all_methods.bg
# add chr prefix
all_methods = pd.read_csv(f'{github_dir}/introgression_maps/all_methods.bg', sep='\t', low_memory=False)
all_methods['chrom'] = 'chr' + all_methods['chrom'].astype(str)
all_methods.to_csv(f'{github_dir}/introgression_maps/all_methods.bg', sep='\t', index=False, header=True)

# boolean version
!cp {HOMEDIR}/introgression_methods/cleaned/introgression_tools/boolean_overlap.bed {github_dir}/introgression_maps/all_methods_boolean.bg
# add chr prefix
all_methods = pd.read_csv(f'{github_dir}/introgression_maps/all_methods_boolean.bg', sep='\t', low_memory=False)
all_methods['chrom'] = 'chr' + all_methods['chrom'].astype(str)
all_methods = pd.read_csv(f'{github_dir}/introgression_maps/all_methods.bg', sep='\t', low_memory=False)
all_methods.to_csv(f'{github_dir}/introgression_maps/all_methods.bg', sep='\t', header=True, index=False, na_rep='NA') # save NA as str
all_methods.to_csv(f'{github_dir}/introgression_maps/all_methods_boolean.bg', sep='\t', index=False, header=True, na_rep='NA') # save NA as str

# 84 CEU version
df = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/supplement_data/84_ceu_individual.bg', sep='\t', low_memory=False)
# add chr prefix
df['Chromosome'] = 'chr' + df['Chromosome'].astype(str)
df[['Chromosome', 'Start', 'End', 'ID', 'Map']].to_csv(f'{github_dir}/introgression_maps/84_shared_CEU.bg', sep='\t', index=False, header=True)

!cp {HOMEDIR}/introgression_methods/cleaned/introgression_tools/african_boolean_overlap.bg {github_dir}/introgression_maps/african_boolean_overlap.bg
# add chr prefix
all_methods = pd.read_csv(f'{github_dir}/introgression_maps/african_boolean_overlap.bg', sep='\t', low_memory=False)
all_methods['chrom'] = 'chr' + all_methods['chrom'].astype(str)
all_methods.to_csv(f'{github_dir}/introgression_maps/african_boolean_overlap.bg', sep='\t', index=False, header=True)


!cp {HOMEDIR}/introgression_methods/cleaned/introgression_tools/african_boolean_overlap_no_admix.bg {github_dir}/introgression_maps/african_boolean_overlap_no_admix.bg
# add chr prefix to no admix version
df = pd.read_csv(f'{github_dir}/introgression_maps/african_boolean_overlap_no_admix.bg', sep='\t', low_memory=False)
df['chrom'] = 'chr' + df['chrom'].astype(str)
df.to_csv(f'{github_dir}/introgression_maps/african_boolean_overlap_no_admix.bg', sep='\t', index=False, header=True)

# 2 afr
df = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/supplement_data/2_afr_individual.bg', sep='\t', low_memory=False)
# add chr prefix
df['Chromosome'] = 'chr' + df['Chromosome'].astype(str)
df[['Chromosome', 'Start', 'End', 'ID', 'Algorithm']].to_csv(f'{github_dir}/introgression_maps/2_shared_afr.bg', sep='\t', index=False, header=True)

# make a maps_by_support directory and read in all_methods.bg, 
os.makedirs(f'{github_dir}/introgression_maps/maps_by_support/min_num_methods', exist_ok=True)
os.makedirs(f'{github_dir}/introgression_maps/maps_by_support/num_methods', exist_ok=True)
# save files by number of methods supporting introgression
all_methods = pd.read_csv(f'{github_dir}/introgression_maps/all_methods.bg', sep='\t', low_memory=False)
# add chr prefix
if all_methods['chrom'].dtype != object:
    if not all_methods['chrom'].iloc[0].astype(str).startswith('chr'):
        all_methods['chrom'] = 'chr' + all_methods['chrom']
# exclude chrom, start, end, and length
cols_sum_across = all_methods.columns.difference(['chrom', 'start', 'end', 'length'])
all_methods['num_methods'] = all_methods[cols_sum_across].notna().sum(axis=1)
# separate x chrom regions
all_methods_x = all_methods[all_methods['chrom'] == 'chrX']
all_methods = all_methods[all_methods['chrom'] != 'chrX']
# make a maps_by_support directory and read in all_methods.bg, 
os.makedirs(f'{github_dir}/introgression_maps/maps_by_support/min_num_methods', exist_ok=True)
os.makedirs(f'{github_dir}/introgression_maps/maps_by_support/num_methods', exist_ok=True)
for number in all_methods.num_methods.unique():
    subset = all_methods[all_methods['num_methods'] >= number]
    subset.to_csv(f'{github_dir}/introgression_maps/maps_by_support/min_num_methods/introgressed_regions_at_least_{number}_methods.bg', sep='\t', index=False, header=True, na_rep='NA')
    subset = all_methods[all_methods['num_methods'] == number]
    subset.to_csv(f'{github_dir}/introgression_maps/maps_by_support/num_methods/introgressed_regions_{number}_methods.bg', sep='\t', index=False, header=True, na_rep='NA')

for number in all_methods_x.num_methods.unique():
    subset = all_methods_x[all_methods_x['num_methods'] >= number]
    subset.to_csv(f'{github_dir}/introgression_maps/maps_by_support/min_num_methods/introgressed_regions_X_at_least_{number}_methods.bg', sep='\t', index=False, header=True, na_rep='NA')
    subset = all_methods_x[all_methods_x['num_methods'] == number]
    subset.to_csv(f'{github_dir}/introgression_maps/maps_by_support/num_methods/introgressed_regions_X_{number}_methods.bg', sep='\t', index=False, header=True, na_rep='NA')

# copy the full map for each method to the corresponding directory in github
for method in methods_dirs:
    source_file = f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/{method}/bedgraphs/union_merged_highest_score.bg'
    dest_file = f'{github_dir}/introgression_maps/maps_by_method/{method}/{method}_regions_merged.bed'
    # remove last column in dest file
    !cp {source_file} {dest_file}
    dest_df = pd.read_csv(dest_file, sep='\t', low_memory=False, names=['chrom', 'start', 'end', 'score'])
    dest_df = dest_df[['chrom', 'start', 'end']]
    # add chr prefix if not there
    print('saving full map for', method)
    if dest_df['chrom'].dtype != object:
        if not dest_df['chrom'].iloc[0].astype(str).startswith('chr'):
            dest_df['chrom'] = 'chr' + dest_df['chrom'].astype(str)
            dest_df.to_csv(dest_file, sep='\t', index=False, header=True)
    elif dest_df['chrom'].dtype == object:
        if not dest_df['chrom'].iloc[0].startswith('chr'):
            dest_df['chrom'] = 'chr' + dest_df['chrom'].astype(str)
            dest_df.to_csv(dest_file, sep='\t', index=False, header=True)

    # copy the map by population (union merged)
    source_file = f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/{method}/bedgraphs/union_merged.bg'
    dest_file = f'{github_dir}/introgression_maps/maps_by_method/{method}/{method}_region_superpop.bg'
    print('saving population map for', method)
    if os.path.exists(source_file):
        !cp {source_file} {dest_file}
        # add chr prefix if not there
        # special case for durvasula and skov 2020 since they don't have a header and only one pop
        if method in ['durvasula_2019', 'skov_2020']:
            dest_df = pd.read_csv(dest_file, sep='\t', low_memory=False, names=['chrom', 'start', 'end', 'EUR'])
            if dest_df['chrom'].dtype != object:
                if not dest_df['chrom'].iloc[0].astype(str).startswith('chr'):
                    dest_df['chrom'] = 'chr' + dest_df['chrom'].astype(str)
                    dest_df.to_csv(dest_file, sep='\t', index=False, header=True)
            elif dest_df['chrom'].dtype == object:
                if not dest_df['chrom'].iloc[0].startswith('chr'):
                    dest_df['chrom'] = 'chr' + dest_df['chrom'].astype(str)
                    dest_df.to_csv(dest_file, sep='\t', index=False, header=True)
        else:
            dest_df = pd.read_csv(dest_file, sep='\t', low_memory=False)
            if dest_df['chrom'].dtype != object:
                if not dest_df['chrom'].iloc[0].astype(str).startswith('chr'):
                    dest_df['chrom'] = 'chr' + dest_df['chrom'].astype(str)
                    dest_df.to_csv(dest_file, sep='\t', index=False, header=True)
            elif dest_df['chrom'].dtype == object:
                if not dest_df['chrom'].iloc[0].startswith('chr'):
                    dest_df['chrom'] = 'chr' + dest_df['chrom'].astype(str)
                    dest_df.to_csv(dest_file, sep='\t', index=False, header=True)

    # copy variant file if it exists
    source_file = f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/{method}/neanderthal_introgressed_variants.bg'
    dest_file = f'{github_dir}/introgression_maps/maps_by_method/{method}/{method}_variants.bed'
    if os.path.exists(source_file):
        !cp {source_file} {dest_file}
        # add chr prefix if not there
        dest_df = pd.read_csv(dest_file, sep='\t', low_memory=False, names=['chrom', 'start', 'end'])
        # check if the column is a string
        print('saving variant file for', method)
        if dest_df['chrom'].dtype != object:
            if not dest_df['chrom'].iloc[0].astype(str).startswith('chr'):
                dest_df['chrom'] = 'chr' + dest_df['chrom'].astype(str)
                dest_df.to_csv(dest_file, sep='\t', index=False, header=True)
        elif dest_df['chrom'].dtype == object:
            if not dest_df['chrom'].iloc[0].startswith('chr'):
                dest_df['chrom'] = 'chr' + dest_df['chrom'].astype(str)
                dest_df.to_csv(dest_file, sep='\t', index=False, header=True)

saving full map for yuan_2021
saving population map for yuan_2021
saving full map for durvasula_2019
saving population map for durvasula_2019
saving full map for steinruecken_2018
saving population map for steinruecken_2018
saving full map for skov_2020
saving population map for skov_2020
saving variant file for skov_2020
saving full map for schaefer_2021
saving population map for schaefer_2021
saving full map for hubisz_2020
saving population map for hubisz_2020
saving full map for browning_2018_updated_filtering
saving population map for browning_2018_updated_filtering
saving variant file for browning_2018_updated_filtering
saving full map for vernot_2016
saving population map for vernot_2016
saving variant file for vernot_2016
saving full map for sankararaman_2014
saving population map for sankararaman_2014
saving variant file for sankararaman_2014
saving full map for sankararaman_2016_1
saving population map for sankararaman_2016_1
saving variant file for sankararaman_2016_1
saving full map for sankararaman_2016_2
saving population map for sankararaman_2016_2
saving variant file for sankararaman_2016_2
saving full map for li_2024
saving population map for li_2024
saving full map for skov_2018
saving population map for skov_2018
saving variant file for skov_2018
saving full map for iasi_2024
saving population map for iasi_2024

In [57]:
%%bash

# hg 38 conversion
LIFTOVERPATH=/wynton/group/capra/bin/liftOver/liftOver
DATADIR=/wynton/home/capra/ychen39/introgression_methods/cleaned/github_data_round_2/github/data
LIFTOVERFILES=/wynton/home/capra/ychen39/introgression_methods/cleaned/github_data/github/data/liftover_files

mkdir $DATADIR/hg38
mkdir $DATADIR/hg38/unlifted
mkdir $DATADIR/hg38/introgression_maps
cd $DATADIR/hg19

# run liftover -- skip first line
# if gzipped, gunzip
if [[ -f $DATADIR/hg19/all_deserts.bg.gz ]]; then
    gunzip -f $DATADIR/hg19/all_deserts.bg.gz
fi
head -n 1 "$DATADIR/hg19/all_deserts.bg" > $DATADIR/hg38/all_deserts.bg
tail -n +2 $DATADIR/hg19/all_deserts.bg | ${LIFTOVERPATH} stdin $LIFTOVERFILES/hg19ToHg38.over.chain stdout $DATADIR/hg38/unlifted/unlifted_all_deserts.bg -bedPlus=3 >> $DATADIR/hg38/all_deserts.bg
#if not already gzipped, gzip the files
if [[ ! -f $DATADIR/hg38/all_deserts.bg.gz ]]; then
    gzip -f $DATADIR/hg38/all_deserts.bg
fi
if [[ ! -f $DATADIR/hg19/all_deserts.bg.gz ]]; then
    gzip -f $DATADIR/hg19/all_deserts.bg
fi

files=('all_methods.bg' 'all_methods_boolean.bg' '84_shared_CEU.bg' 'african_boolean_overlap_no_admix.bg' 'african_boolean_overlap.bg' '2_shared_afr.bg')

for file in "${files[@]}"; do
    echo "Lifting over ${file}"
    if [[ -f $DATADIR/hg19/introgression_maps/$file.gz ]]; then
        gunzip -f $DATADIR/hg19/introgression_maps/$file.gz
    fi
    head -n 1 "$DATADIR/hg19/introgression_maps/$file" > $DATADIR/hg38/introgression_maps/$file
    tail -n +2 $DATADIR/hg19/introgression_maps/$file | ${LIFTOVERPATH} stdin $LIFTOVERFILES/hg19ToHg38.over.chain stdout $DATADIR/hg38/unlifted/unlifted_$file -bedPlus=3 >> $DATADIR/hg38/introgression_maps/$file
    if [[ ! -f $DATADIR/hg38/introgression_maps/$file.gz ]]; then
        gzip -f $DATADIR/hg38/introgression_maps/$file
    fi
    if [[ ! -f $DATADIR/hg19/introgression_maps/$file.gz ]]; then
        gzip -f $DATADIR/hg19/introgression_maps/$file
    fi
done

# now for each individual introgression dir file

mkdir $DATADIR/hg38/introgression_maps/maps_by_method/

for dir in $(ls $DATADIR/hg19/introgression_maps/maps_by_method/); do
    
    mkdir $DATADIR/hg38/introgression_maps/maps_by_method/${dir}

    for file in $(ls $DATADIR/hg19/introgression_maps/maps_by_method/$dir/); do
        echo "Lifting over ${file} for method ${dir}"
        # write header line and liftover
        head -n 1 "$DATADIR/hg19/introgression_maps/maps_by_method/${dir}/${file}" > $DATADIR/hg38/introgression_maps/maps_by_method/${dir}/${file}
        tail -n +2 $DATADIR/hg19/introgression_maps/maps_by_method/${dir}/${file} | ${LIFTOVERPATH} stdin $LIFTOVERFILES/hg19ToHg38.over.chain stdout $DATADIR/hg38/unlifted/unlifted_${file} -bedPlus=3 >> $DATADIR/hg38/introgression_maps/maps_by_method/${dir}/${file}
        gzip -f $DATADIR/hg38/introgression_maps/maps_by_method/${dir}/${file}
        gzip -f $DATADIR/hg19/introgression_maps/maps_by_method/${dir}/${file}
    done
done

# now for maps by support

mkdir $DATADIR/hg38/introgression_maps/maps_by_support/

for dir in $(ls $DATADIR/hg19/introgression_maps/maps_by_support/); do
    
    mkdir $DATADIR/hg38/introgression_maps/maps_by_support/${dir}

    for file in $(ls $DATADIR/hg19/introgression_maps/maps_by_support/$dir/); do
        
        head -n 1 "$DATADIR/hg19/introgression_maps/maps_by_support/${dir}/${file}" > $DATADIR/hg38/introgression_maps/maps_by_support/${dir}/${file}
        tail -n +2 $DATADIR/hg19/introgression_maps/maps_by_support/${dir}/${file} | ${LIFTOVERPATH} stdin $LIFTOVERFILES/hg19ToHg38.over.chain stdout $DATADIR/hg38/unlifted/unlifted_${file} -bedPlus=3 >> $DATADIR/hg38/introgression_maps/maps_by_support/${dir}/${file}
        gzip -f $DATADIR/hg38/introgression_maps/maps_by_support/${dir}/${file}
        gzip -f $DATADIR/hg19/introgression_maps/maps_by_support/${dir}/${file}
    
    done
done

Reading liftover chains
Mapping coordinates

Lifting over all_methods.bg

Reading liftover chains
Mapping coordinates

Lifting over all_methods_boolean.bg

Reading liftover chains
Mapping coordinates

Lifting over 84_shared_CEU.bg

Reading liftover chains
Mapping coordinates

Lifting over african_boolean_overlap_no_admix.bg

Reading liftover chains
Mapping coordinates

Lifting over african_boolean_overlap.bg

Reading liftover chains
Mapping coordinates

Lifting over 2_shared_afr.bg

Reading liftover chains
Mapping coordinates

Lifting over browning_2018_updated_filtering_regions_merged.bed for method browning_2018_updated_filtering

Reading liftover chains
Mapping coordinates

Lifting over browning_2018_updated_filtering_region_superpop.bg for method browning_2018_updated_filtering

Reading liftover chains
Mapping coordinates

Lifting over browning_2018_updated_filtering_variants.bed for method browning_2018_updated_filtering

Reading liftover chains
Mapping coordinates

Lifting over durvasula_2019_regions_merged.bed for method durvasula_2019

Reading liftover chains
Mapping coordinates

Lifting over durvasula_2019_region_superpop.bg for method durvasula_2019

Reading liftover chains
Mapping coordinates

Lifting over hubisz_2020_regions_merged.bed for method hubisz_2020

Reading liftover chains
Mapping coordinates

Lifting over hubisz_2020_region_superpop.bg for method hubisz_2020

Reading liftover chains
Mapping coordinates

Lifting over iasi_2024_regions_merged.bed for method iasi_2024

Reading liftover chains
Mapping coordinates

Lifting over iasi_2024_region_superpop.bg for method iasi_2024

Reading liftover chains
Mapping coordinates

Lifting over li_2024_regions_merged.bed for method li_2024

Reading liftover chains
Mapping coordinates

Lifting over li_2024_region_superpop.bg for method li_2024

Reading liftover chains
Mapping coordinates

Lifting over sankararaman_2014_regions_merged.bed for method sankararaman_2014

Reading liftover chains
Mapping coordinates

Lifting over sankararaman_2014_region_superpop.bg for method sankararaman_2014

Reading liftover chains
Mapping coordinates

Lifting over sankararaman_2014_variants.bed for method sankararaman_2014

Reading liftover chains
Mapping coordinates

Lifting over sankararaman_2016_1_regions_merged.bed for method sankararaman_2016_1

Reading liftover chains
Mapping coordinates

Lifting over sankararaman_2016_1_region_superpop.bg for method sankararaman_2016_1

Reading liftover chains
Mapping coordinates

Lifting over sankararaman_2016_1_variants.bed for method sankararaman_2016_1

Reading liftover chains
Mapping coordinates

Lifting over sankararaman_2016_2_regions_merged.bed for method sankararaman_2016_2

Reading liftover chains
Mapping coordinates

Lifting over sankararaman_2016_2_region_superpop.bg for method sankararaman_2016_2

Reading liftover chains
Mapping coordinates

Lifting over sankararaman_2016_2_variants.bed for method sankararaman_2016_2

Reading liftover chains
Mapping coordinates

Lifting over schaefer_2021_regions_merged.bed for method schaefer_2021

Reading liftover chains
Mapping coordinates

Lifting over schaefer_2021_region_superpop.bg for method schaefer_2021

Reading liftover chains
Mapping coordinates

Lifting over skov_2018_regions_merged.bed for method skov_2018

Reading liftover chains
Mapping coordinates

Lifting over skov_2018_region_superpop.bg for method skov_2018

Reading liftover chains
Mapping coordinates

Lifting over skov_2018_variants.bed for method skov_2018

Reading liftover chains
Mapping coordinates

Lifting over skov_2020_regions_merged.bed for method skov_2020

Reading liftover chains
Mapping coordinates

Lifting over skov_2020_region_superpop.bg for method skov_2020

Reading liftover chains
Mapping coordinates

Lifting over skov_2020_variants.bed for method skov_2020

Reading liftover chains
Mapping coordinates

Lifting over steinruecken_2018_regions_merged.bed for method steinruecken_2018

Reading liftover chains
Mapping coordinates

Lifting over steinruecken_2018_region_superpop.bg for method steinruecken_2018

Reading liftover chains
Mapping coordinates

Lifting over vernot_2016_regions_merged.bed for method vernot_2016

Reading liftover chains
Mapping coordinates

Lifting over vernot_2016_region_superpop.bg for method vernot_2016

Reading liftover chains
Mapping coordinates

Lifting over vernot_2016_variants.bed for method vernot_2016

Reading liftover chains
Mapping coordinates

Lifting over yuan_2021_regions_merged.bed for method yuan_2021

Reading liftover chains
Mapping coordinates

Lifting over yuan_2021_region_superpop.bg for method yuan_2021

Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates
Reading liftover chains
Mapping coordinates

In [58]:
%%bash

# T2T conversion
LIFTOVERPATH=/wynton/group/capra/bin/liftOver/liftOver
DATADIR=/wynton/home/capra/ychen39/introgression_methods/cleaned/github_data_round_2/github/data
LIFTOVERFILES=/wynton/home/capra/ychen39/introgression_methods/cleaned/github_data/github/data/liftover_files

mkdir $DATADIR/T2T
mkdir $DATADIR/T2T/unlifted
mkdir $DATADIR/T2T/introgression_maps
cd $DATADIR/hg19

# run liftover -- skip first line
# if gzipped, gunzip
if [[ -f $DATADIR/hg19/all_deserts.bg.gz ]]; then
    gunzip -f $DATADIR/hg19/all_deserts.bg.gz
fi
head -n 1 "$DATADIR/hg19/all_deserts.bg" > $DATADIR/T2T/all_deserts.bg
tail -n +2 $DATADIR/hg19/all_deserts.bg | ${LIFTOVERPATH} stdin $LIFTOVERFILES/hg19ToHs1.over.chain stdout $DATADIR/T2T/unlifted/unlifted_all_deserts.bg -bedPlus=3 >> $DATADIR/T2T/all_deserts.bg
#if not already gzipped, gzip the files
if [[ ! -f $DATADIR/T2T/all_deserts.bg.gz ]]; then
    gzip -f $DATADIR/T2T/all_deserts.bg
fi
if [[ ! -f $DATADIR/hg19/all_deserts.bg.gz ]]; then
    gzip -f $DATADIR/hg19/all_deserts.bg
fi

files=('all_methods.bg' 'all_methods_boolean.bg' '84_shared_CEU.bg' 'african_boolean_overlap_no_admix.bg' 'african_boolean_overlap.bg' '2_shared_afr.bg')

for file in "${files[@]}"; do
    echo "Lifting over ${file}"
    if [[ -f $DATADIR/hg19/introgression_maps/$file.gz ]]; then
        gunzip -f $DATADIR/hg19/introgression_maps/$file.gz
    fi
    head -n 1 "$DATADIR/hg19/introgression_maps/$file" > $DATADIR/T2T/introgression_maps/$file
    tail -n +2 $DATADIR/hg19/introgression_maps/$file | ${LIFTOVERPATH} stdin $LIFTOVERFILES/hg19ToHs1.over.chain stdout $DATADIR/T2T/unlifted/unlifted_$file -bedPlus=3 >> $DATADIR/T2T/introgression_maps/$file
    if [[ ! -f $DATADIR/T2T/introgression_maps/$file.gz ]]; then
        gzip -f $DATADIR/T2T/introgression_maps/$file
    fi
    if [[ ! -f $DATADIR/hg19/introgression_maps/$file.gz ]]; then
        gzip -f $DATADIR/hg19/introgression_maps/$file
    fi
done

# now for each individual introgression dir file

mkdir $DATADIR/T2T/introgression_maps/maps_by_method/

for dir in $(ls $DATADIR/hg19/introgression_maps/maps_by_method/); do
    
    mkdir $DATADIR/T2T/introgression_maps/maps_by_method/${dir}

    for file in $(ls $DATADIR/hg19/introgression_maps/maps_by_method/$dir/); do
        echo "Lifting over ${file} for method ${dir}"
        # write header line and liftover
        if [[ -f $DATADIR/hg19/introgression_maps/maps_by_method/${dir}/${file}.gz ]]; then
            gunzip -f $DATADIR/hg19/introgression_maps/maps_by_method/${dir}/${file}.gz
        fi
        head -n 1 "$DATADIR/hg19/introgression_maps/maps_by_method/${dir}/${file}" > $DATADIR/T2T/introgression_maps/maps_by_method/${dir}/${file}
        tail -n +2 $DATADIR/hg19/introgression_maps/maps_by_method/${dir}/${file} | ${LIFTOVERPATH} stdin $LIFTOVERFILES/hg19ToHs1.over.chain stdout $DATADIR/T2T/unlifted/unlifted_${file} -bedPlus=3 >> $DATADIR/T2T/introgression_maps/maps_by_method/${dir}/${file}
        if [[ ! -f $DATADIR/T2T/introgression_maps/maps_by_method/${dir}/${file}.gz ]]; then
            gzip -f $DATADIR/T2T/introgression_maps/maps_by_method/${dir}/${file}
        fi
        
        if [[ ! -f $DATADIR/hg19/introgression_maps/maps_by_method/${dir}/${file}.gz ]]; then
            gzip -f $DATADIR/hg19/introgression_maps/maps_by_method/${dir}/${file}
        fi
    done
done

# now for maps by support

mkdir $DATADIR/T2T/introgression_maps/maps_by_support/

for dir in $(ls $DATADIR/hg19/introgression_maps/maps_by_support/); do
    
    mkdir $DATADIR/T2T/introgression_maps/maps_by_support/${dir}

    for file in $(ls $DATADIR/hg19/introgression_maps/maps_by_support/$dir/); do
        
        if [[ -f $DATADIR/hg19/introgression_maps/maps_by_support/${dir}/${file}.gz ]]; then
            gunzip -f $DATADIR/hg19/introgression_maps/maps_by_support/${dir}/${file}.gz
        fi
        head -n 1 "$DATADIR/hg19/introgression_maps/maps_by_support/${dir}/${file}" > $DATADIR/T2T/introgression_maps/maps_by_support/${dir}/${file}
        tail -n +2 $DATADIR/hg19/introgression_maps/maps_by_support/${dir}/${file} | ${LIFTOVERPATH} stdin $LIFTOVERFILES/hg19ToHs1.over.chain stdout $DATADIR/T2T/unlifted/unlifted_${file} -bedPlus=3 >> $DATADIR/T2T/introgression_maps/maps_by_support/${dir}/${file}
        
        if [[ ! -f $DATADIR/T2T/introgression_maps/maps_by_support/${dir}/${file}.gz ]]; then
            gzip -f $DATADIR/T2T/introgression_maps/maps_by_support/${dir}/${file}
        fi
        
        if [[ ! -f $DATADIR/hg19/introgression_maps/maps_by_support/${dir}/${file}.gz ]]; then
            gzip -f $DATADIR/hg19/introgression_maps/maps_by_support/${dir}/${file}
        fi
    
    done
done

Reading liftover chains
Mapping coordinates

Lifting over all_methods.bg

Reading liftover chains
Mapping coordinates

Lifting over all_methods_boolean.bg

Reading liftover chains
Mapping coordinates

Lifting over 84_shared_CEU.bg

Reading liftover chains
Mapping coordinates

Lifting over african_boolean_overlap_no_admix.bg

Reading liftover chains
Mapping coordinates

Lifting over african_boolean_overlap.bg

Reading liftover chains
Mapping coordinates

Lifting over 2_shared_afr.bg

Reading liftover chains
Mapping coordinates

Lifting over browning_2018_updated_filtering_regions_merged.bed.gz for method browning_2018_updated_filtering

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got E�VF�م��w������toH�vN�~��jW|��NĮ��}�B�7뮽���m���y�\kٽvnm�x���r�c�\]|ؗK�k�~ŗ��c�X

Lifting over browning_2018_updated_filtering_region_superpop.bg.gz for method browning_2018_updated_filtering

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over browning_2018_updated_filtering_variants.bed.gz for method browning_2018_updated_filtering

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over durvasula_2019_regions_merged.bed.gz for method durvasula_2019

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got ��Ij���o��

Lifting over durvasula_2019_region_superpop.bg.gz for method durvasula_2019

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over hubisz_2020_regions_merged.bed.gz for method hubisz_2020

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over hubisz_2020_region_superpop.bg.gz for method hubisz_2020

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 2 of stdin, got >KS�W\G

Lifting over iasi_2024_regions_merged.bed.gz for method iasi_2024

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got !mʮ�������r/���yc�v�ȫ���s��9��&����ҾN�6���۞7�����������QHi�ȡ�?�

Lifting over iasi_2024_region_superpop.bg.gz for method iasi_2024

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got ��_k�*�1�ʇ"cJO*�T8S�ho�&�:���[�*�S��(�*w��3��V�ƞhD��q#��L=����o�6P)�xcL~Oۮ�|

Lifting over li_2024_regions_merged.bed.gz for method li_2024

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over li_2024_region_superpop.bg.gz for method li_2024

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over sankararaman_2014_regions_merged.bed.gz for method sankararaman_2014

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over sankararaman_2014_region_superpop.bg.gz for method sankararaman_2014

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over sankararaman_2014_variants.bed.gz for method sankararaman_2014

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got ��_�a�Ob��k_��y��k_:�

Lifting over sankararaman_2016_1_regions_merged.bed.gz for method sankararaman_2016_1

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over sankararaman_2016_1_region_superpop.bg.gz for method sankararaman_2016_1

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over sankararaman_2016_1_variants.bed.gz for method sankararaman_2016_1

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got ]�\�mi������������l��@�w���Зζ&t�j{�З�^~{��gV%����7��g���P�*d�4Ki�=�U~u����ݾ���]�G_�k���}n��=�~c�n����[�

Lifting over sankararaman_2016_2_regions_merged.bed.gz for method sankararaman_2016_2

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over sankararaman_2016_2_region_superpop.bg.gz for method sankararaman_2016_2

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over sankararaman_2016_2_variants.bed.gz for method sankararaman_2016_2

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over schaefer_2021_regions_merged.bed.gz for method schaefer_2021

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over schaefer_2021_region_superpop.bg.gz for method schaefer_2021

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got �(a

Lifting over skov_2018_regions_merged.bed.gz for method skov_2018

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got ��D�:.�lL�

Lifting over skov_2018_region_superpop.bg.gz for method skov_2018

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over skov_2018_variants.bed.gz for method skov_2018

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got �{�p�i#���>^�Y]�W]�^��L����nS���������[�}����Jq��ݎ_J��#q���l�=�;l��^

Lifting over skov_2020_regions_merged.bed.gz for method skov_2020

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over skov_2020_region_superpop.bg.gz for method skov_2020

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over skov_2020_variants.bed.gz for method skov_2020

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over steinruecken_2018_regions_merged.bed.gz for method steinruecken_2018

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over steinruecken_2018_region_superpop.bg.gz for method steinruecken_2018

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over vernot_2016_regions_merged.bed.gz for method vernot_2016

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over vernot_2016_region_superpop.bg.gz for method vernot_2016

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over vernot_2016_variants.bed.gz for method vernot_2016

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over yuan_2021_regions_merged.bed.gz for method yuan_2021

Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

Lifting over yuan_2021_region_superpop.bg.gz for method yuan_2021

Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got 6:m��R��O'�¿����=�(�-�2X�`8��b���jB����|�f|��l�m'ۈ��~��b'��6�?�������꬟���B���'_�V}�#7R�.�3�69�YЈ����.(i��w�FN���|(��/��I)yk�|��TL5$�G�`좺ۂ��wA����ݜ�
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got ??�Y2��la��ݕ�l��{
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got D�Ԃ��Nõ����-I-p�L6
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got �/���p1�����a+F?eC1�D�"[���;��^�Z�X8_�ܤW0��)aD��>�Cř\�M�bY�m�hrl��e�V����5���l�1�M;X
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got �ף�R
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got ���1eW��������p�o0��HY�Cy�H�*�w��H�*�ՠ�
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got �p'~��n@9si�V�ҝ�_�`�������,&�)\�3�p�S�?��̡3m�b�;µ����G
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got %��?�Btd�e���BzCz���?R�IE%������5h�K�%���
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got D�Ԃ��Nõ����-I-p�L6
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got �N��Y
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got ��h5x��
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got �!�s�"YT�I~.-GqH�R��H�1U��[K*E�E}
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Expecting integer field 2 line 1 of stdin, got %->��e���w��۔>����7��;���)q�˰����똳�DY�w6>��/�bς��
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)
Reading liftover chains
Mapping coordinates
Data format error: expecting at least 3 fields in BED file (stdin)

# Generate files for rGREAT

Here I generate the overall Neanderhal introgression background file, where any region considered introgressed, regardless of method, is included.

Also: 
- overlap_11_high_support_no_archie_argweaver: 11+ methods supporting (highly supported regions), no archie/argweaver
- overlap_11_high_support_with_archie_argweaver: 11+ methods support (highly-supported regions), including archie/argweaver
- overlap_12_no_archie_argweaver: All 12 methods overlapping, no archie/Argweaver
- overlap_14_high_support_with_archie_argweaver: All 14 methods overlapping, including archie/argweaver
- 11+ methods support, all neanderthal maps as background

In [ ]:
# background file containing all regions that were considered introgressed (all_methods.bed file that we previously created)
# need to remove the last columns
# directory to store data
!mkdir {HOMEDIR}/introgression_methods/data/GREAT_analysis
!mkdir {HOMEDIR}/introgression_methods/data/GREAT_analysis/input
overlap = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed', sep='\t', low_memory=False)
nean_background = overlap[['chrom', 'start', 'end']]
nean_background['chrom'] = 'chr' + nean_background['chrom'].astype(str)
nean_background.to_csv(f'{HOMEDIR}/introgression_methods/data/GREAT_analysis/nean_background.bed', sep='\t', index=False, header=False)
# merge overlapping entries that were previously separated due to counting the overlap between different sets of methods, now we are not worried about a score associated with each introgressed region
!$BEDTOOLSDIR/bedtools merge -i {HOMEDIR}/introgression_methods/data/GREAT_analysis/nean_background.bed > {HOMEDIR}/introgression_methods/data/GREAT_analysis/nean_background_merged.bed
# remove unmerged file
!rm {HOMEDIR}/introgression_methods/data/GREAT_analysis/nean_background.bed

mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/data/GREAT_analysis’: File exists
mkdir: cannot create directory ‘/wynton/home/capra/ychen39//introgression_methods/data/GREAT_analysis/input’: File exists

I will generate test files for different introgressed regions I want to test, and background files containing all regions that contain introgression.

Here is a function to generate non-overlapping bed files with each method as the test set, and all detected Neanderthal introgressed regions as the background set (the background set must contain identical test set entries, plus other regions that are part of the background).

In [ ]:
# GREAT requires background file to contain exactly the same entries as the test, plus extra background regions as separate entries
# subtract all nean introgression regions - test introgression set to get extra introgressed regions
def GREAT_background_files(method_name=None, test_df=None, test_df_path=None):
    if test_df_path is not None:
        df = pd.read_csv(f'{test_df_path}', sep='\t', low_memory=False, names=['chrom', 'start', 'end'])
    elif test_df is not None:
        df = test_df
    # add chr prefix if the column contains integers
    if df['chrom'].dtype != 'str':
        df['chrom'] = 'chr' + df['chrom'].astype(str)
    test_bed = df[['chrom', 'start', 'end']]
    test_bed.to_csv(f'{HOMEDIR}/introgression_methods/data/GREAT_analysis/{method_name}_GREAT.bed', sep='\t', index=False, header=False)
    !$BEDTOOLSDIR/bedtools merge -i {HOMEDIR}/introgression_methods/data/GREAT_analysis/{method_name}_GREAT.bed > {HOMEDIR}/introgression_methods/data/GREAT_analysis/input/{method_name}_GREAT_merged.bed
    # remove unmerged file
    # subtract test regions from full nean background file 
    !$BEDTOOLSDIR/bedtools subtract -a {HOMEDIR}/introgression_methods/data/GREAT_analysis/nean_background_merged.bed \
    -b {HOMEDIR}/introgression_methods/data/GREAT_analysis/input/{method_name}_GREAT_merged.bed > {HOMEDIR}/introgression_methods/data/GREAT_analysis/background_sub_{method_name}.bed
    # append original test regions to nean introgressed regions (subtracted test from full nean background file)
    !cat {HOMEDIR}/introgression_methods/data/GREAT_analysis/input/{method_name}_GREAT_merged.bed {HOMEDIR}/introgression_methods/data/GREAT_analysis/background_sub_{method_name}.bed > {HOMEDIR}/introgression_methods/data/GREAT_analysis/{method_name}_background.bed
    # re-sort regions
    !$BEDTOOLSDIR/bedtools sort -i {HOMEDIR}/introgression_methods/data/GREAT_analysis/{method_name}_background.bed > {HOMEDIR}/introgression_methods/data/GREAT_analysis/input/{method_name}_background_GREAT.bed

In [ ]:
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/li_2024/bedgraphs/union_merged_prefix.bg', method_name='ibdmix')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/hubisz_2020/bedgraphs/union_merged_prefix.bg', method_name='argweaverd')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/yuan_2021/bedgraphs/union_merged_prefix.bg', method_name='archaicseeker')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/durvasula_2019/bedgraphs/union_merged_prefix.bg', method_name='archie')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/browning_2018_updated_filtering/bedgraphs/union_merged_prefix.bg', method_name='sprime')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/vernot_2016/bedgraphs/union_merged_prefix.bg', method_name='vernot2016')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2014/bedgraphs/union_merged_prefix.bg', method_name='sankararaman2014')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_1/bedgraphs/union_merged_prefix.bg', method_name='sankararaman2016_1')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/sankararaman_2016_2/bedgraphs/union_merged_prefix.bg', method_name='sankararaman2016_2')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2020/bedgraphs/union_merged_prefix.bg', method_name='skov2020')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/skov_2018/bedgraphs/union_merged_prefix.bg', method_name='skov2018')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/steinruecken_2018/bedgraphs/union_merged_prefix.bg', method_name='steinruecken2018')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/schaefer_2021/bedgraphs/union_merged_prefix.bg', method_name='sarge')
GREAT_background_files(test_df_path=f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/iasi_2024/bedgraphs/union_merged_prefix.bg', method_name='admixfrog')

I want to test if regions overlapping across all 13 methods have specific genomic elements compared to the background. Additionally, I will repeat the test but excluding ArchIE and ARGweaver-D which have small test sets to look at regions overlapping over the remaining 10 methods (high-confidence Neanderthal introgressed methods).

In [ ]:
# Generate bed file with all 13 methods overlapping
overlap = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed', sep='\t', low_memory=False)

overlap_14_methods = overlap.dropna()
overlap_14_methods = overlap_14_methods[['chrom', 'start', 'end']]

GREAT_background_files('overlap_14_methods_with_archieargweaver', test_df=overlap_14_methods) # HAS ENRICHMENTS: lots of telomere processes, ATPase activity

In [ ]:
overlap_12_methods = overlap.drop(columns=['archie', 'argweaverd'])
overlap_12_methods = overlap_12_methods.dropna()
overlap_12_methods_great = overlap_12_methods[['chrom', 'start', 'end']]

GREAT_background_files('overlap_12_no_archie_argweaver', test_df=overlap_12_methods_great) # no enrichments under default parameters

11+ methods supporting (highly supported regions), no archie/argweaver: 

I will also generate GREAT files where at least 11 methods support a region (excluding ArchIE and ARGweaver-D), high supporting regions

In [ ]:
overlap = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed', sep='\t', low_memory=False)
overlap.replace(0, np.nan, inplace=True)
# List of columns to exclude to make boolean
exclude_columns = ['chrom', 'start', 'end', 'length', 'archie', 'argweaverd']
overlap[overlap.columns.difference(exclude_columns)] = overlap[overlap.columns.difference(exclude_columns)].apply(lambda x: pd.notna(x))

# methods cols to check for boolean
columns_to_check = [item for item in overlap.columns if item not in exclude_columns]

# keep rows with at least 11 TRUE values
mask = overlap[columns_to_check].fillna(False).astype(bool).sum(axis=1) >= 11

# filter the original DataFrame based on the mask
overlap_11_more = overlap[mask]
overlap_11_more # number matches the num support plot

GREAT_background_files('overlap_11_high_support_no_archie_argweaver', test_df=overlap_11_more[['chrom', 'start', 'end']])

In [ ]:
overlap_11_more

,chrom,start,end,argweaverd,archaicseeker,archie,sprime,vernot_2016,sankararaman_2014,sankararaman_2016_1,sankararaman_2016_2,hmmix20,steinruecken_2018,sarge,hmmix18,admixfrog,ibdmix24,length
379,1,2932446,2934733,NaN,True,NaN,True,True,True,True,True,True,True,True,True,False,True,2287
381,1,2935600,2940998,NaN,True,NaN,True,True,True,True,True,True,True,True,True,False,True,5398
382,1,2940998,2941778,NaN,True,NaN,True,True,True,True,True,True,True,True,True,False,True,780
384,1,2943882,2950001,NaN,True,NaN,True,True,True,True,True,True,True,True,True,False,True,6119
385,1,2950001,2953712,NaN,True,NaN,True,True,True,True,True,True,True,True,True,False,True,3711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442243,9,137692832,137693864,NaN,True,NaN,False,True,True,True,True,True,True,True,True,True,True,1032
442244,9,137693864,137695750,NaN,True,NaN,False,True,True,True,True,True,True,True,True,True,True,1886
442245,9,137695750,137696355,NaN,True,NaN,False,True,True,True,True,True,True,True,True,True,True,605
442248,9,137700845,137710162,NaN,True,NaN,False,True,True,True,True,True,True,True,True,True,True,9317
442249,9,137710162,137714950,NaN,True,0.983573,False,True,True,True,True,True,True,True,True,True,True,4788

In [ ]:
overlap_11_more

,chrom,start,end,argweaverd,archaicseeker,archie,sprime,vernot_2016,sankararaman_2014,sankararaman_2016_1,sankararaman_2016_2,hmmix20,steinruecken_2018,sarge,hmmix18,admixfrog,ibdmix24,length
379,1,2932446,2934733,NaN,True,NaN,True,True,True,True,True,True,True,True,True,False,True,2287
381,1,2935600,2940998,NaN,True,NaN,True,True,True,True,True,True,True,True,True,False,True,5398
382,1,2940998,2941778,NaN,True,NaN,True,True,True,True,True,True,True,True,True,False,True,780
384,1,2943882,2950001,NaN,True,NaN,True,True,True,True,True,True,True,True,True,False,True,6119
385,1,2950001,2953712,NaN,True,NaN,True,True,True,True,True,True,True,True,True,False,True,3711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442243,9,137692832,137693864,NaN,True,NaN,False,True,True,True,True,True,True,True,True,True,True,1032
442244,9,137693864,137695750,NaN,True,NaN,False,True,True,True,True,True,True,True,True,True,True,1886
442245,9,137695750,137696355,NaN,True,NaN,False,True,True,True,True,True,True,True,True,True,True,605
442248,9,137700845,137710162,NaN,True,NaN,False,True,True,True,True,True,True,True,True,True,True,9317
442249,9,137710162,137714950,NaN,True,0.983573,False,True,True,True,True,True,True,True,True,True,True,4788

11+ methods support (highly-supported regions), including archie/argweaver

In [ ]:
overlap = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed', sep='\t', low_memory=False)
overlap.replace(0, np.nan, inplace=True)
# List of columns to exclude to make boolean
exclude_columns = ['chrom', 'start', 'end', 'length']
overlap[overlap.columns.difference(exclude_columns)] = overlap[overlap.columns.difference(exclude_columns)].apply(lambda x: pd.notna(x))

# methods cols to check for boolean
columns_to_check = [item for item in overlap.columns if item not in exclude_columns]

# keep rows with at least 11 TRUE values
mask = overlap[columns_to_check].fillna(False).astype(bool).sum(axis=1) >= 11

# filter the original DataFrame based on the mask
overlap_11_more = overlap[mask]
overlap_11_more # number matches the num support plot

GREAT_background_files('overlap_11_high_support_with_archie_argweaver', test_df=overlap_11_more[['chrom', 'start', 'end']])

In [ ]:
overlap_11_more

,chrom,start,end,argweaverd,archaicseeker,archie,sprime,vernot_2016,sankararaman_2014,sankararaman_2016_1,sankararaman_2016_2,hmmix20,steinruecken_2018,sarge,hmmix18,admixfrog,ibdmix24,length
379,1,2932446,2934733,False,True,False,True,True,True,True,True,True,True,True,True,False,True,2287
381,1,2935600,2940998,False,True,False,True,True,True,True,True,True,True,True,True,False,True,5398
382,1,2940998,2941778,False,True,False,True,True,True,True,True,True,True,True,True,False,True,780
384,1,2943882,2950001,False,True,False,True,True,True,True,True,True,True,True,True,False,True,6119
385,1,2950001,2953712,False,True,False,True,True,True,True,True,True,True,True,True,False,True,3711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442723,9,138569536,138570425,False,True,True,False,True,True,True,True,True,True,True,True,False,True,889
442725,9,138580126,138590329,False,True,True,False,True,True,True,True,True,True,True,True,False,True,10203
442727,9,138592775,138605915,False,True,True,False,True,True,True,True,True,True,True,True,False,True,13140
442728,9,138605915,138608347,False,True,True,False,True,True,True,True,True,True,True,True,False,True,2432
442730,9,138608463,138609749,False,True,True,False,True,True,True,True,True,True,True,True,False,True,1286

All 12 methods overlapping, no archie/Argweaver

In [ ]:
overlap = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed', sep='\t', low_memory=False)
overlap.replace(0, np.nan, inplace=True)
# List of columns to exclude to make boolean
exclude_columns = ['chrom', 'start', 'end', 'length', 'archie', 'argweaverd']
overlap[overlap.columns.difference(exclude_columns)] = overlap[overlap.columns.difference(exclude_columns)].apply(lambda x: pd.notna(x))

# methods cols to check for boolean
columns_to_check = [item for item in overlap.columns if item not in exclude_columns]

# keep rows with at least 11 TRUE values
mask = overlap[columns_to_check].fillna(False).astype(bool).sum(axis=1) == 12

# filter the original DataFrame based on the mask
overlap_12_more = overlap[mask]
overlap_12_more # number matches the num support plot

GREAT_background_files('overlap_12_high_support_no_archie_argweaver', test_df=overlap_12_more[['chrom', 'start', 'end']])

In [ ]:
overlap_12_more

,chrom,start,end,argweaverd,archaicseeker,archie,sprime,vernot_2016,sankararaman_2014,sankararaman_2016_1,sankararaman_2016_2,hmmix20,steinruecken_2018,sarge,hmmix18,admixfrog,ibdmix24,length
548,1,3336790,3336841,NaN,True,0.970477,True,True,True,True,True,True,True,True,True,True,True,51
549,1,3336841,3339059,NaN,True,0.970477,True,True,True,True,True,True,True,True,True,True,True,2218
550,1,3339059,3340770,NaN,True,0.970477,True,True,True,True,True,True,True,True,True,True,True,1711
551,1,3340770,3340837,NaN,True,0.970477,True,True,True,True,True,True,True,True,True,True,True,67
557,1,3360951,3362564,NaN,True,0.970477,True,True,True,True,True,True,True,True,True,True,True,1613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442228,9,137661713,137661778,NaN,True,NaN,True,True,True,True,True,True,True,True,True,True,True,65
442229,9,137661778,137661869,NaN,True,NaN,True,True,True,True,True,True,True,True,True,True,True,91
442230,9,137661869,137665284,NaN,True,NaN,True,True,True,True,True,True,True,True,True,True,True,3415
442231,9,137665284,137666959,NaN,True,NaN,True,True,True,True,True,True,True,True,True,True,True,1675
442237,9,137686335,137686987,NaN,True,NaN,True,True,True,True,True,True,True,True,True,True,True,652

- All 14 methods overlapping, including archie/argweaver

In [ ]:
overlap = pd.read_csv(f'{HOMEDIR}/introgression_methods/cleaned/introgression_tools/all_methods.bed', sep='\t', low_memory=False)
overlap.replace(0, np.nan, inplace=True)
# List of columns to exclude to make boolean
exclude_columns = ['chrom', 'start', 'end', 'length']
overlap[overlap.columns.difference(exclude_columns)] = overlap[overlap.columns.difference(exclude_columns)].apply(lambda x: pd.notna(x))

# methods cols to check for boolean
columns_to_check = [item for item in overlap.columns if item not in exclude_columns]

# keep rows with at least 11 TRUE values
mask = overlap[columns_to_check].fillna(False).astype(bool).sum(axis=1) == 14

# filter the original DataFrame based on the mask
overlap_14_more = overlap[mask]
overlap_14_more # number matches the num support plot

GREAT_background_files('overlap_14_high_support_with_archie_argweaver', test_df=overlap_14_more[['chrom', 'start', 'end']])